const translations = {

  tr: {
    bgUrl: "Arka Plan URL:",
    font: "Yazı Tipi:",
    theme: "Renk Teması:",
    accentColor: "Vurgu Rengi:",
    language: "Dil:",
    logoDisplay: "Logo Görünümü:",
    system: "Sistem",
    searchEngine: "Arama Motoru:",
    showFavorites: "Favorileri Göster:",
    maxFavorites: "Maksimum Favori Sayısı:",
    showSuggestions: "Arama Önerilerini Göster:",
    showWeather: "Hava Durumunu Göster:",
    weatherLocation: "Hava Durumu Konumu:",
    showInfoBar: "Bilgi Barını Göster:",
    weatherUpdateInterval: "Hava Durumu Güncelleme Sıklığı:",
    linkBehavior: "Link Davranışı:",
    apply: "Uygula",
    favoriteName: "İsim:",
    favoriteUrl: "URL:",
    add: "Ekle",
    search: "Ara",
    images: "Görseller",
    shopping: "Alışveriş",
    news: "Haberler",
    addFavorite: " + ",
    dark: "Koyu",
    light: "Açık",
    logoOnly: "Sadece Logo",
    logoAndName: "Logo ve İsim",
    none: "Hiçbiri",
    yes: "Evet",
    no: "Hayır",
    every5Min: "Her 5 Dakika",
    every10Min: "Her 10 Dakika",
    every30Min: "Her 30 Dakika",
    manual: "Manuel",
    newTab: "Yeni Sekmede Aç",
    closeCurrent: "Bu Sayfayı Kapat",
    searchPlaceholder: "Arama yap...",
    favoritePlaceholder: "Favori ismi",
    urlPlaceholder: "https://...",
    weatherLocationPlaceholder: "Şehir ismi",
    languageDisplay: "Türkçe",
    maxFavoritesAlert: "Maksimum favori sayısına ulaşıldı!",
    invalidUrlAlert: "Geçerli bir URL girin (örn: https://example.com).",
    voiceSearchNotSupported: "Sesli arama tarayıcınızda desteklenmiyor. Lütfen metin araması kullanın.",
    weatherError: "Hava durumu yüklenemedi.",
    personalization: "Kişiselleştirme",
    shortcuts: "Klavye Kısayolları",
    searchShortcut: "Arama Çubuğu:",
    favoriteShortcut: "Favori Ekle:",
    settingsShortcut: "Ayarlar Paneli:",
    historyShortcut: "Geçmiş Paneli:",
    imagesShortcut: "Görseller Araması:",
    shoppingShortcut: "Alışveriş Araması:",
    newsShortcut: "Haberler Araması:",
    searchHistory: "Arama Geçmişi",
    clearHistory: "Geçmişi Temizle",
    noHistory: "Geçmiş arama yok.",
    account: "Hesap",
    login: "Giriş Yap",
    register: "Kayıt Ol",
    logout: "Çıkış Yap",
    welcome: "Hoşgeldiniz",
    usernamePlaceholder: "Kullanıcı adı",
    passwordPlaceholder: "Şifre",
    accountTitle: "Hesap",
    accountLogin: "Hesap (Giriş için tıklayın)",
    accountLoggedIn: "Hesap (Çıkış için tıklayın)",
    accountError: "Hatalı kullanıcı adı veya şifre.",
    usernameTooShort: "Kullanıcı adı en az 2 karakter olmalı.",
    passwordTooShort: "Şifre en az 4 karakter olmalı.",
    usernameTaken: "Bu kullanıcı adı zaten alınmış.",
    confirm: "Tamam",
    cancel: "İptal",
    voiceSearch: "Söyledikleriniz burada görünecek...",
    aiProvider: "AI Sağlayıcı:",
    customAiUrl: "Özel AI URL:",
    showAISearch: "AI Aramasını Göster:",
    aiShortcut: "AI Arama Kısayolu:",
    aiSearch: "AI Arama",
    accountIcon: "Hesap Simgesi",
    weather: "Hava Durumu",
    weatherApi: "Hava Durumu API",
    openWeatherMapApiKey: "OpenWeatherMap API Anahtarı:",
    visualCrossingApiKey: "Visual Crossing API Anahtarı:",
    weatherApiKey: "Hava Durumu API Anahtarı:",
    settings: "Ayarlar",
    history: "Geçmiş",
    loading: "Yükleniyor...",
    weatherLocationEmpty: "Lütfen bir konum girin.",
    weatherApiKeyMissing: "API anahtarı eksik.",
    weatherClear: "Açık",
    weatherPartlyCloudy: "Parçalı Bulutlu",
    weatherCloudy: "Bulutlu",
    weatherRain: "Yağmurlu",
    weatherSnow: "Karlı",
    weatherWindy: "Rüzgarlı",
    weatherFog: "Sisli",
    weatherShower: "Sağanak Yağışlı",
    weatherLightRain: "Hafif Yağmur",
    noLocation: "Lütfen bir konum girin.",
    youtubeError: "YouTube videosu yüklenemedi.",
    resetConfirm: "Tüm ayarları ve verileri sıfırlamak istediğinize emin misiniz?",
    resetSuccess: "Tarayıcı başarıyla sıfırlandı!",
    feedbackMessage: "Şikayet/Geri Bildirim",
    feedbackScreenshot: "Ekran Görüntüsü (isteğe bağlı)",
    submitFeedback: "Geri Bildirim Gönder",
    feedbackSuccess: "Geri bildirim başarıyla gönderildi!",
    feedbackError: "Geri bildirim gönderilirken hata oluştu",
    invalidImage: "Lütfen geçerli bir resim dosyası seçin",
    fileTooLarge: "Dosya boyutu 5MB'dan büyük olamaz"
  },
  az: {
bgUrl: "Arxa Plan URL:",
font: "Şrift:",
theme: "Rəng Teması:",
accentColor: "Vurğu Rəngi:",
language: "Dil:",
logoDisplay: "Loqo Görünüşü:",
system: "Sistem",
searchEngine: "Axtarış Mühərriki:",
showFavorites: "Sevimliləri Göstər:",
maxFavorites: "Sevimlilərin Maksimum Sayı:",
showSuggestions: "Axtarış Təkliflərini Göstər:",
showWeather: "Hava Vəziyyətini Göstər:",
weatherLocation: "Hava Vəziyyəti Yeri:",
showInfoBar: "Məlumat Panelini Göstər:",
weatherUpdateInterval: "Hava Yeniləmə Aralığı:",
linkBehavior: "Link Davranışı:",
apply: "Tətbiq Et",
favoriteName: "Ad:",
favoriteUrl: "URL:",
add: "Əlavə Et",
search: "Axtar",
images: "Şəkillər",
shopping: "Alış-veriş",
news: "Xəbərlər",
addFavorite: " + ",
dark: "Tünd",
light: "Açıq",
logoOnly: "Yalnız Loqo",
logoAndName: "Loqo və Ad",
none: "Heç biri",
yes: "Bəli",
no: "Xeyr",
every5Min: "Hər 5 dəqiqə",
every10Min: "Hər 10 dəqiqə",
every30Min: "Hər 30 dəqiqə",
manual: "Əl ilə",
newTab: "Yeni Sekmede Aç",
closeCurrent: "Cari Səhifəni Bağla",
searchPlaceholder: "Axtar...",
favoritePlaceholder: "Sevimli adı",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Şəhər adı",
languageDisplay: "Azərbaycanca",
maxFavoritesAlert: "Sevimlilərin maksimum sayına çatdı!",
invalidUrlAlert: "Zəhmət olmasa, etibarlı bir URL daxil edin (məs.: https://example.com).",
voiceSearchNotSupported: "Səsli axtarış brauzerinizdə dəstəklənmir. Zəhmət olmasa, mətn axtarışını istifadə edin.",
weatherError: "Hava məlumatları yüklənə bilmədi.",
personalization: "Şəxsiləşdirmə",
shortcuts: "Klaviatura Qısayolları",
searchShortcut: "Axtarış Çubuq:",
favoriteShortcut: "Sevimli Əlavə Et:",
settingsShortcut: "Quraşdırma Paneli:",
historyShortcut: "Tarix Paneli:",
imagesShortcut: "Şəkil Axtarışı:",
shoppingShortcut: "Alış-veriş Axtarışı:",
newsShortcut: "Xəbər Axtarışı:",
searchHistory: "Axtarış Tarixi",
clearHistory: "Tarixi Təmizlə",
noHistory: "Axtarış tarixi yoxdur.",
account: "Hesab",
login: "Daxil ol",
register: "Qeydiyyatdan keç",
logout: "Çıx",
welcome: "Xuş gəldiniz",
usernamePlaceholder: "İstifadəçi adı",
passwordPlaceholder: "Şifrə",
accountTitle: "Hesab",
accountLogin: "Hesab (Daxil olmaq üçün tıklayın)",
accountLoggedIn: "Hesab (Çıxış üçün tıklayın)",
accountError: "Yanlış istifadəçi adı və ya şifrə.",
usernameTooShort: "İstifadəçi adı ən az 2 simvol olmalıdır.",
passwordTooShort: "Şifrə ən az 4 simvol olmalıdır.",
usernameTaken: "Bu istifadəçi adı artıq alınmışdır.",
confirm: "Tamam",
cancel: "Ləğv et",
voiceSearch: "Deyilənlər burada görsənəcək...",
  aiProvider: "AI Təchizatçı:",
    customAiUrl: "Xüsusi AI URL:",
    showAISearch: "AI Axtarışını Göstər:",
    aiShortcut: "AI Axtarışı:",
    accountIcon: "Hesab İkonu",
    weather: "Hava",
    weatherApi: "Hava API",
    openWeatherMapApiKey: "OpenWeatherMap API Anahtarı",
    visualCrossingApiKey: "Visual Crossing API Anahtarı",
    weatherApiKey: "Hava API Anahtarı:",
    aiSearch: "AI Axtarışı",
    settings: "Quraşdırma",
    history: "Tarix",
    weatherLoading: "Yükleniyor...",
    weatherError: "Hava durumu alınamadı",
    weatherLocationEmpty: "Lütfen bir konum girin",
    weatherApiKeyMissing: "API anahtarı eksik",
    weatherClear: "Açıq",
    weatherPartlyCloudy: "Bölünmüş Buludlu",
    weatherCloudy: "Buludlu",
    weatherRain: "Yağışlı",
    weatherSnow: "Qar",
    weatherWindy: "Küləkli",
    weatherFog: "Dumanlı",
    weatherShower: "Yağış",
    weatherLightRain: "Yüngül Yağış",
    loading: "Yükleniyor...",
    noLocation: "Lütfen bir konum girin",
    youtubeError: "YouTube videosu yüklenemedi",
    resetConfirm: "Tüm ayarları ve verileri sıfırlamak istediğinize emin misiniz?",
    resetSuccess: "Tarayıcı başarıyla sıfırlandı!",
},
tk: {
bgUrl: "Arka plan URL-si:",
font: "Şrift:",
theme: "Reňk Temasy:",
accentColor: "Accent Reňki:",
language: "Dil:",
logoDisplay: "Logotip Görkezişi:",
system: "Sistema",
searchEngine: "Gözleg Ulgamy:",
showFavorites: "Halanlary Görkez:",
maxFavorites: "Halanlaryň Maksimum Sanysy:",
showSuggestions: "Gözleg Tekliplerini Görkez:",
showWeather: "Howa Durumyny Görkez:",
weatherLocation: "Howa ýeri:",
showInfoBar: "Maglumat Panelini Görkez:",
weatherUpdateInterval: "Howa Yangylama Aralygy:",
linkBehavior: "Baglanyşyk Özgerişi:",
apply: "Ulanyň",
favoriteName: "Ady:",
favoriteUrl: "URL:",
add: "Goş",
search: "Gözle",
images: "Suratlar",
shopping: "Satyn Alma",
news: "Habarlar",
addFavorite: " + ",
dark: "Garaňky",
light: "Ýagty",
logoOnly: "Diňe Logotip",
logoAndName: "Logotip we Ady",
none: "Hiç zat",
yes: "Hawa",
no: "Ýok",
every5Min: "Her 5 minut",
every10Min: "Her 10 minut",
every30Min: "Her 30 minut",
manual: "Elle",
newTab: "Täze Ýapjykda Aç",
closeCurrent: "Häzirki Sahypany Ýap",
searchPlaceholder: "Gözle...",
favoritePlaceholder: "Halan ady",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Şäher ady",
languageDisplay: "Türkmençe",
maxFavoritesAlert: "Halanlaryň maksimum sanysy ýetildi!",
invalidUrlAlert: "Dogry URL giriň (mysal: https://example.com).",
voiceSearchNotSupported: "Sesli gözleg brauzeriňizde goldanmaýar. Metin gözlegini ulanyň.",
weatherError: "Howa maglumatlary ýüklänmedi.",
personalization: "Şahsylaşdyrma",
shortcuts: "Klawiýatura Gysga Ýollary",
searchShortcut: "Gözleg Çyzgy:",
favoriteShortcut: "Halan Goş:",
settingsShortcut: "Sazlama Paneli:",
historyShortcut: "Geçmiş Paneli:",
imagesShortcut: "Surat Gözlegi:",
shoppingShortcut: "Satyn Alma Gözlegi:",
newsShortcut: "Habar Gözlegi:",
searchHistory: "Gözleg Geçmişi",
clearHistory: "Geçmişi Arassala",
noHistory: "Gözleg geçmişi ýok.",
account: "Hasap",
login: "Giriş",
register: "Registrasiýa",
logout: "Çyk",
welcome: "Hoş geldiňiz",
usernamePlaceholder: "Ulanyjy ady",
passwordPlaceholder: "Açar söz",
accountTitle: "Hasap",
accountLogin: "Hasap (Giriş üçin basyň)",
accountLoggedIn: "Hasap (Çykmak üçin basyň)",
accountError: "Nädogry ulanyjy ady ýa-da açar söz.",
usernameTooShort: "Ulanyjy ady iň az 2 harpdan ybarat bolmaly.",
passwordTooShort: "Açar söz iň az 4 harpdan ybarat bolmaly.",
usernameTaken: "Bu ulanyjy ady eýýäm alnan.",
confirm: "Bolýar",
cancel: "Ýatyrmak",
voiceSearch: "Aýdýanlaryňyz şu ýerde görkeziler...",
  aiProvider: "AI Üpjünçi:",
    customAiUrl: "Aýratyn AI URL:",
    showAISearch: "AI Gözlegini Görkez:",
    aiShortcut: "AI Gözlegi:",
    accountIcon: "Hasap Ikony",
    weather: "Hava",
    weatherApi: "Hava API",
    openWeatherMapApiKey: "OpenWeatherMap API Anahtary",
    visualCrossingApiKey: "Visual Crossing API Anahtary",
    weatherApiKey: "Hava API Anahtary:",
    aiSearch: "AI Axtarışı",
    settings: "Sazlamalar",
    history: "Tarix",
    weatherLoading: "Yükleniyor...",
    weatherError: "Hava durumu alınamadı",
    weatherLocationEmpty: "Lütfen bir konum girin",
    weatherApiKeyMissing: "API anahtarı eksik",
    weatherClear: "Açyk",
    weatherPartlyCloudy: "Bölünip Bulutly",
    weatherCloudy: "Bulutly",
    weatherRain: "Ýagmur",
    weatherSnow: "Gurak",
    weatherWindy: "Şamally",
    weatherFog: "Syz",
    weatherShower: "Ýagmur",
    weatherLightRain: "Hafif Ýagmur",
    loading: "Yükleniyor...",
    noLocation: "lütfen bir konum girin",
    youtubeError: "YouTube videosu yüklenemedi",
    resetConfirm: "Tüm ayarları ve verileri sıfırlamak istediğinize emin misiniz?",
    resetSuccess: "Tarayıcı başarıyla sıfırlandı!",
},
kk: {
bgUrl: "Фон URL:",
font: "Қаріп:",
theme: "Ренг Темасы:",
accentColor: "Басым Түс:",
language: "Тіл:",
logoDisplay: "Логотип Көрінісі:",
system: "Жүйе",
searchEngine: "Іздеу Жүйесі:",
showFavorites: "Таңдаулыларды Көрсету:",
maxFavorites: "Таңдаулылардың Максималды Санын:",
showSuggestions: "Іздеу Ұсыныстарын Көрсету:",
showWeather: "Ауа Райын Көрсету:",
weatherLocation: "Ауа Райы Орны:",
showInfoBar: "Ақпарат Жолағын Көрсету:",
weatherUpdateInterval: "Ауа Райы Жаңарту Аралығы:",
linkBehavior: "Сілтеме Әрекеті:",
apply: "Қолдану",
favoriteName: "Атауы:",
favoriteUrl: "URL:",
add: "Қосу",
search: "Іздеу",
images: "Суреттер",
shopping: "Сатып Алу",
news: "Жаңалықтар",
addFavorite: " + ",
dark: "Қараңғы",
light: "Жарық",
logoOnly: "Тек Логотип",
logoAndName: "Логотип пен Атау",
none: "Ешнәрсе",
yes: "Иә",
no: "Жоқ",
every5Min: "Әр 5 Минутта",
every10Min: "Әр 10 Минутта",
every30Min: "Әр 30 Минутта",
manual: "Қолмен",
newTab: "Жаңа Бетте Ашу",
closeCurrent: "Ағымдағы Бетті Жабу",
searchPlaceholder: "Іздеу...",
favoritePlaceholder: "Таңдаулы атауы",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Қала атауы",
languageDisplay: "Қазақша",
maxFavoritesAlert: "Таңдаулылардың максималды санына жетті!",
invalidUrlAlert: "Өтініш, жарамды URL енгізіңіз (мысалы: https://example.com).",
voiceSearchNotSupported: "Дауыстық іздеу сіздің браузерде қолдау көрсетілмейді. Мәтіндік іздеуді қолданыңыз.",
weatherError: "Ауа райы ақпараты жүктелмеді.",
personalization: "Жеке Баптау",
shortcuts: "Перне Тізбегі Қысқартулары",
searchShortcut: "Іздеу Жолағы:",
favoriteShortcut: "Таңдаулы Қосу:",
settingsShortcut: "Баптау Панелі:",
historyShortcut: "Тарих Панелі:",
imagesShortcut: "Сурет Іздеу:",
shoppingShortcut: "Сатып Алу Іздеу:",
newsShortcut: "Жаңалықтар Іздеу:",
searchHistory: "Іздеу Тарихы",
clearHistory: "Тарихты Тазалау",
noHistory: "Іздеу тарихы жоқ.",
account: "Есеп",
login: "Кіру",
register: "Тіркелу",
logout: "Шығу",
welcome: "Қош келдіңіз",
usernamePlaceholder: "Пайдаланушы аты",
passwordPlaceholder: "Құпия сөз",
accountTitle: "Есеп",
accountLogin: "Есеп (Кіру үшін басыңыз)",
accountLoggedIn: "Есеп (Шығу үшін басыңыз)",
accountError: "Қате пайдаланушы аты немесе құпия сөз.",
usernameTooShort: "Пайдаланушы аты кемінде 2 таңбадан тұруы керек.",
passwordTooShort: "Құпия сөз кемінде 4 таңбадан тұруы керек.",
usernameTaken: "Бұл пайдаланушы аты бұрыннан алынған.",
confirm: "OK",
cancel: "Бас тарту",
voiceSearch: "Айтқан сөздеріңіз осында көрінеді...",
   aiProvider: "AI Провайдері:",
    customAiUrl: "Арнайы AI URL:",
    showAISearch: "AI Іздеуді Көрсету:",
    aiShortcut: "AI Іздеу:",
    accountIcon: "Есеп Белгішесі",
    weather: "Ауа-райы",
    weatherApi: "Ауа-райы API",
    openWeatherMapApiKey: "OpenWeatherMap API Кілті",
    visualCrossingApiKey: "Visual Crossing API Кілті",
    weatherApiKey: "Weather API Кілті:",
    aiSearch: "AI Издөө",
    settings: "Баптаулар",
    history: "Тарых",
    weatherLoading: "Жүктөлүүдө...",
    weatherError: "Аба ырайы алынган жок",
    weatherLocationEmpty: "Сураныч, бир жайгашууну киргизиңиз",
    weatherApiKeyMissing: "API ачкычы жетишпейт",
    weatherClear: "Ашық",
    weatherPartlyCloudy: "Кысмен булуттуу",
    weatherCloudy: "Булуттуу",
    weatherRain: "Жаан",
    weatherSnow: "Кар",
    weatherWindy: "Шамалдуу",
    weatherFog: "Туман",
    weatherShower: "Жаан",
    weatherLightRain: "Жеңил жаан",
    loading: "Жүктөлүүдө...",
    noLocation: "Сураныч, бир жайгашууну киргизиңиз",
    youtubeError: "YouTube видеосу жүктөлгөн жок",
    resetConfirm: "Бардык жөндөөлөрдү жана маалыматтарды нөлдөп салууга ишенесизби?",
    resetSuccess: "Браузер ийгиликтүү нөлдөндү!",
},
ky: {
bgUrl: "Фон URL:",
font: "Арип:",
theme: "Тема:",
accentColor: "Басым Ранг:",
language: "Тил:",
logoDisplay: "Логотип Көргөзмө:",
system: "Система",
searchEngine: "Издөө Жабдыкчасы:",
showFavorites: "Сүйүктүүдөрдү Көргөзүү:",
maxFavorites: "Сүйүктүүдөрдүн Максималдуу Санын:",
showSuggestions: "Издөө Сунуштарын Көргөзүү:",
showWeather: "Аба Ырайын Көргөзүү:",
weatherLocation: "Аба Ырайы Жери:",
showInfoBar: "Маалымат Чубугун Көргөзүү:",
weatherUpdateInterval: "Аба Ырайын Жаңырту Интервалы:",
linkBehavior: "Байланыш Жүрүм Туруму:",
apply: "Колдонуу",
favoriteName: "Аты:",
favoriteUrl: "URL:",
add: "Кошуу",
search: "Издөө",
images: "Сүрөттөр",
shopping: "Сатып Алуу",
news: "Жаңылыктар",
addFavorite: " + ",
dark: "Караңгы",
light: "Жарык",
logoOnly: "Бир гана Логотип",
logoAndName: "Логотип жана Аты",
none: "Эч нерсе",
yes: "Ооба",
no: "Жок",
every5Min: "Ар бир 5 мүнөттө",
every10Min: "Ар бир 10 мүнөттө",
every30Min: "Ар бир 30 мүнөттө",
manual: "Кол менен",
newTab: "Жаңы Бетте Ачуу",
closeCurrent: "Учурдагы Бетти Жабуу",
searchPlaceholder: "Издөө...",
favoritePlaceholder: "Сүйүктүү аты",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Шаар аты",
languageDisplay: "Кыргызча",
maxFavoritesAlert: "Сүйүктүүдөрдүн максималдуу санына жетти!",
invalidUrlAlert: "Зарыл, туура URL киргизиңиз (мисалы: https://example.com).",
voiceSearchNotSupported: "Үн менен издөө сиздин браузериңизде колдоого алынбайт. Тексттик издөөнү колдонуңуз.",
weatherError: "Аба ырайы маалыматтары жүктөлгөн жок.",
personalization: "Жеке Баптоо",
shortcuts: "Перне Таңгактары Кыска Жолдору",
searchShortcut: "Издөө Чубугун:",
favoriteShortcut: "Сүйүктүү Кошуу:",
settingsShortcut: "Жөндөө Панели:",
historyShortcut: "Тарых Панели:",
imagesShortcut: "Сүрөт Издөөсү:",
shoppingShortcut: "Сатып Алуу Издөөсү:",
newsShortcut: "Жаңылыктар Издөөсү:",
searchHistory: "Издөө Тарыхы",
clearHistory: "Тарыхты Таза Кылуу",
noHistory: "Издөө тарыхы жок.",
account: "Каттоо",
login: "Кирүү",
register: "Каттоо",
logout: "Чыгуу",
welcome: "Кош келиңиз",
usernamePlaceholder: "Колдонуучу аты",
passwordPlaceholder: "Сыр сөз",
accountTitle: "Каттоо",
accountLogin: "Каттоо (Кирүү үчүн чыкылдатыңыз)",
accountLoggedIn: "Каттоо (Чыгуу үчүн чыкылдатыңыз)",
accountError: "Жараксыз колдонуучу аты же сыр сөз.",
usernameTooShort: "Колдонуучу аты кеминде 2 тамгадан турушу керек.",
passwordTooShort: "Сыр сөз кеминде 4 тамгадан турушу керек.",
usernameTaken: "Бул колдонуучу аты мурунтан алынган.",
confirm: "Макул",
cancel: "Жокко чыгаруу",
voiceSearch: "Айткандарыңыз бул жерде көрүнөт...",
   aiProvider: "AI Провайдери:",
    customAiUrl: "Атайын AI URL:",
    showAISearch: "AI Іздеуді Көргөзүү:",
    aiShortcut: "AI Іздеу:",
    accountIcon: "Каттоо Белгиси",
    weather: "Ауа-райы",
    weatherApi: "Ауа-райы API",
    openWeatherMapApiKey: "OpenWeatherMap API Кілті",
    visualCrossingApiKey: "Visual Crossing API Кілті",
    weatherApiKey: "Ауа-райы API Кілті:",
    aiSearch: "AI Издөө",
    settings: "Баптаулар",
    history: "Тарых",
    weatherLoading: "Жүктөлүүдө...",
    weatherError: "Аба ырайы алынган жок",
    weatherLocationEmpty: "Сураныч, бир жайгашууну киргизиңиз",
    weatherApiKeyMissing: "API ачкычы жетишпейт",
    weatherApiKeyInvalid: "API ачкычы туура эмес",
    weatherLocationNotFound: "Аба ырайы жайгашуусу табылган жок",
    weatherLocationError: "Аба ырайы жайгашуусу катасы",
    weatherDataError: "Аба ырайы маалыматы катасы",
    loading: "Жүктөлүүдө...",
    noLocation: "Сураныч, бир жайгашууну киргизиңиз",
    youtubeError: "YouTube видеосу жүктөлгөн жок",
    resetConfirm: "Бардык жөндөөлөрдү жана маалыматтарды нөлдөп салууга ишенесизби?",
    resetSuccess: "Браузер ийгиликтүү нөлдөндү!",
    weatherClear: "Кулпун",
    weatherPartlyCloudy: "Кулпун",
    weatherCloudy: "BКулпун",
    weatherRain: "YoКулпун",
    weatherSnow: "Кулпун",
    weatherWindy: "ShКулпун",
    weatherFog: "TumКулпун",
    weatherLightRain: "Yengil Кулпун",

},
uz: {
bgUrl: "Fon URL:",
font: "Shrift:",
theme: "Rang Temasi:",
accentColor: "Accent Rangi:",
language: "Til:",
logoDisplay: "Logotip Ko'rinishi:",
system: "Tizim",
searchEngine: "Qidiruv Dvigateli:",
showFavorites: "Sevimlilarni Ko'rsatish:",
maxFavorites: "Sevimlilarning Maksimal Soni:",
showSuggestions: "Qidiruv Takliflarini Ko'rsatish:",
showWeather: "Ob-havoni Ko'rsatish:",
weatherLocation: "Ob-havo Joyi:",
showInfoBar: "Ma'lumot Panelini Ko'rsatish:",
weatherUpdateInterval: "Ob-havo Yangilanish Oralig'i:",
linkBehavior: "Havola Harakati:",
apply: "Qo'llash",
favoriteName: "Nomi:",
favoriteUrl: "URL:",
add: "Qo'shish",
search: "Qidirish",
images: "Rasmlar",
shopping: "Xarid Qilish",
news: "Yangiliklar",
addFavorite: " + ",
dark: "Qorong'i",
light: "Yorug'",
logoOnly: "Faqat Logotip",
logoAndName: "Logotip va Nom",
none: "Hech narsa",
yes: "Ha",
no: "Yo'q",
every5Min: "Har 5 daqiqada",
every10Min: "Har 10 daqiqada",
every30Min: "Har 30 daqiqada",
manual: "Qo'l bilan",
newTab: "Yangi Varaqada Ochish",
closeCurrent: "Joriy Sahifani Yopish",
searchPlaceholder: "Qidirish...",
favoritePlaceholder: "Sevimli nomi",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Shahar nomi",
languageDisplay: "O'zbekcha",
maxFavoritesAlert: "Sevimlilarning maksimal soniga yetildi!",
invalidUrlAlert: "Iltimos, haqiqiy URL kiriting (masalan: https://example.com).",
voiceSearchNotSupported: "Ovozli qidirish sizning brauzeringizda qo'llab-quvvatlanmaydi. Iltimos, matn qidiruvini ishlatib ko'ring.",
weatherError: "Ob-havo ma’lumotlari yuklanmadi.",
personalization: "Shaxsiylashtirish",
shortcuts: "Klaviature Kichik Yo'llari",
searchShortcut: "Qidirish Chizig'i:",
favoriteShortcut: "Sevimli Qo'shish:",
settingsShortcut: "Sozlamalar Paneli:",
historyShortcut: "Tarix Paneli:",
imagesShortcut: "Rasmlar Qidiruvi:",
shoppingShortcut: "Xarid Qidiruvi:",
newsShortcut: "Yangiliklar Qidiruvi:",
searchHistory: "Qidiruv Tarixi",
clearHistory: "Tarixni Tozalash",
noHistory: "Qidiruv tarixi yo'q.",
account: "Hisob",
login: "Kirish",
register: "Ro'yxatdan o'tish",
logout: "Chiqish",
welcome: "Xush kelibsiz",
usernamePlaceholder: "Foydalanuvchi nomi",
passwordPlaceholder: "Parol",
accountTitle: "Hisob",
accountLogin: "Hisob (Kirish uchun bosing)",
accountLoggedIn: "Hisob (Chiqish uchun bosing)",
accountError: "Not'o'g'ri foydalanuvchi nomi yoki parol.",
usernameTooShort: "Foydalanuvchi nomi kamida 2 ta harfdan iborat bo'lishi kerak.",
passwordTooShort: "Parol kamida 4 ta harfdan iborat bo'lishi kerak.",
usernameTaken: "Bu foydalanuvchi nomi allaqachon olingan.",
confirm: "OK",
cancel: "Bekor qilish",
voiceSearch: "Aytganlaringiz shu yerda ko'rinadi...",
   aiProvider: "AI Provayderi:",
    customAiUrl: "Maxsus AI URL:",
    showAISearch: "AI Qidiruvni Ko'rsatish:",
    aiShortcut: "AI Qidiruv:",
    accountIcon: "Hisob Ikonasi",
    weather: "Havo",
    weatherApi: "Havo API",
    openWeatherMapApiKey: "OpenWeatherMap API Kaliti",
    visualCrossingApiKey: "Visual Crossing API Kaliti",
    weatherApiKey: "Havo API Kaliti:",
    aiSearch: "AI Qidiruv",
    settings: "Ayarlar",
    history: "Tarix",
    weatherLoading: "Yuklanmoqda...",
    weatherError: "Havo ma’lumotlari yuklanmadi.",
    weatherLocationEmpty: "Iltimos, bir joy kiriting.",
    weatherApiKeyMissing: "API kaliti yo'q.",
    weatherApiKeyInvalid: "API kaliti noto'g'ri.",
    weatherLocationNotFound: "Havo ma’lumotlari joyi topilmadi.",
    weatherLocationError: "Havo ma’lumotlari joyi xatosi",
    weatherDataError: "Havo ma’lumotlari xatosi",
    weatherClear: "Ochiq",
    weatherPartlyCloudy: "Qisman bulutli",
    weatherCloudy: "Bulutli",
    weatherRain: "Yomg'ir",
    weatherSnow: "Qor",
    weatherWindy: "Shamolli",
    weatherFog: "Tuman",
    weatherShower: "Yomg'ir",
    weatherLightRain: "Yengil yomg'ir",
    loading: "Yuklanmoqda...",
    noLocation: "Iltimos, bir joy kiriting.",
    youtubeError: "YouTube videosi yuklanmadi.",
    resetConfirm: "Barcha sozlamalarni va ma'lumotlarni noldan boshlashni xohlaysizmi?",
    resetSuccess: "Brauzer muvaffaqiyatli noldan boshlandi!"

},
tt: {
bgUrl: "Фон URL:",
font: "Хәреф:",
theme: "Рәң Темасы:",
accentColor: "Аксент Төсе:",
language: "Тел:",
logoDisplay: "Логотип Күрсәтү:",
system: "Система",
searchEngine: "Эзләү Моторы:",
showFavorites: "Фаворитларны Күрсәтү:",
maxFavorites: "Фаворитларның Максималь Санын:",
showSuggestions: "Эзләү Тәкъдимнәрен Күрсәтү:",
showWeather: "Һава Торышын Күрсәтү:",
weatherLocation: "Һава Торышы Урыны:",
showInfoBar: "Мәгълүмат Панелен Күрсәтү:",
weatherUpdateInterval: "Һава Торышы Яңарту Аралыгы:",
linkBehavior: "Сылтама Хәрәкәте:",
apply: "Куллану",
favoriteName: "Исем:",
favoriteUrl: "URL:",
add: "Өстәү",
search: "Эзләү",
images: "Рәсемнәр",
shopping: "Сатып Алу",
news: "Яңалыклар",
addFavorite: " + ",
dark: "Караңгы",
light: "Якты",
logoOnly: "Тик Логотип",
logoAndName: "Логотип һәм Исем",
none: "Бер нәрсә дә юк",
yes: "Әйе",
no: "Юк",
every5Min: "Һәр 5 минут",
every10Min: "Һәр 10 минут",
every30Min: "Һәр 30 минут",
manual: "Кул белән",
newTab: "Яңа Биттә Ачу",
closeCurrent: "Хәзерге Битне Ябу",
searchPlaceholder: "Эзләү...",
favoritePlaceholder: "Фаворит исеме",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Шәһәр исеме",
languageDisplay: "Татарча",
maxFavoritesAlert: "Фаворитларның максималь санына җитте!",
invalidUrlAlert: "Зинһар, дөрес URL кертегез (мисал: https://example.com).",
voiceSearchNotSupported: "Тавышлы эзләү сезнең браузерыгызда кулланылмый. Текст эзләвен кулланыгыз.",
weatherError: "Һава торышы мәгълүматлары йөкләнмәде.",
personalization: "Шәхсиләштерү",
shortcuts: "Клавиатура Кыска Юллары",
searchShortcut: "Эзләү Чыбыгы:",
favoriteShortcut: "Фаворит Өстәү:",
settingsShortcut: "Көйләү Панеле:",
historyShortcut: "Тарих Панеле:",
imagesShortcut: "Рәсем Эзләве:",
shoppingShortcut: "Сатып Алу Эзләве:",
newsShortcut: "Яңалыклар Эзләве:",
searchHistory: "Эзләү Тарихы",
clearHistory: "Тарихны Тазалау",
noHistory: "Эзләү тарихы юк.",
account: "Хисап",
login: "Керү",
register: "Теркәлү",
logout: "Чыгу",
welcome: "Рәхим итегез",
usernamePlaceholder: "Кулланучы исеме",
passwordPlaceholder: "Серсүз",
accountTitle: "Хисап",
accountLogin: "Хисап (Керү өчен басыгыз)",
accountLoggedIn: "Хисап (Чыгу өчен басыгыз)",
accountError: "Ялгыш кулланучы исеме яки серсүз.",
usernameTooShort: "Кулланучы исеме кимендә 2 символдан торырга тиеш.",
passwordTooShort: "Серсүз кимендә 4 символдан торырга тиеш.",
usernameTaken: "Бу кулланучы исеме инде алынган.",
confirm: "Әйе",
cancel: "Бетерү",
voiceSearch: "Сөйләгәннәрегез монда күренәчәк...",
   aiProvider: "AI Тәэмин Итүче:",
    customAiUrl: "Махсус AI URL:",
    showAISearch: "AI Эзләүне Күрсәтү:",
    aiShortcut: "AI Эзләү:",
    accountIcon: "Хисап Иконкасы",
    weather: "Һава",
    weatherApi: "Һава API",
    openWeatherMapApiKey: "OpenWeatherMap API Ключы",
    visualCrossingApiKey: "Visual Crossing API Ключы",
    weatherApiKey: "Һава API Ключы:",
    aiSearch: "AI Эзләү",
    settings: "Баптаулар",
    history: "Тарых",
    weatherLoading: "Жүктөлүүдө...",
    weatherError: "Аба ырайы алынган жок",
    weatherLocationEmpty: "Сураныч, бир жайгашууну киргизиңиз",
    weatherApiKeyMissing: "API ачкычы жетишпейт",
    weatherClear: "Ачык",
    weatherPartlyCloudy: "Кысмен булуттуу",
    weatherCloudy: "Булуттуу",
    weatherRain: "Жамгыр",
    weatherSnow: "Кар",
    weatherWindy: "Шамалдуу",
    weatherFog: "Туман",
    weatherShower: "Жамгыр",
    weatherLightRain: "Жеңил жамгыр",
        loading: "Жүктөлүүдө...",
        noLocation: "Жайгашуу киргизилген жок",
        youtubeError: "YouTube видеосу жүктөлгөн жок",
        resetConfirm: "Бардык жөндөөлөрдү жана маалыматтарды нөлдөп салууга ишенесизби?",
        resetSuccess: "Браузер ийгиликтүү нөлдөндү!"
},
ba: {
bgUrl: "Фон URL:",
font: "Хәреф:",
theme: "Төҫ Темасы:",
accentColor: "Аксент Төҫө:",
language: "Тел:",
logoDisplay: "Логотип Күрһәтеү:",
system: "Система",
searchEngine: "Эҙләү Моторы:",
showFavorites: "Фавориттарҙы Күрһәтеү:",
maxFavorites: "Фавориттарҙың Максималь Санын:",
showSuggestions: "Эҙләү Тәҡдимдәрен Күрһәтеү:",
showWeather: "Һава Торошон Күрһәтеү:",
weatherLocation: "Һава Торошо Урыны:",
showInfoBar: "Мәғлүмәт Панелен Күрһәтеү:",
weatherUpdateInterval: "Һава Торошо Яңыртыу Арауығы:",
linkBehavior: "Бәйләнеш Хәрәкәте:",
apply: "Ҡулланыу",
favoriteName: "Исем:",
favoriteUrl: "URL:",
add: "Өҫтәү",
search: "Эҙләү",
images: "Рәсемдәр",
shopping: "Һатыу",
news: "Яңылыҡтар",
addFavorite: " + ",
dark: "Ҡараңғы",
light: "Яҡты",
logoOnly: "Тик Логотип",
logoAndName: "Логотип һәм Исем",
none: "Һис бер нәмә лә юҡ",
yes: "Эйе",
no: "Юҡ",
every5Min: "Һәр 5 минут",
every10Min: "Һәр 10 минут",
every30Min: "Һәр 30 минут",
manual: "Кул менән",
newTab: "Яңы Биттә Асыу",
closeCurrent: "Хәҙерге Битте Ябыу",
searchPlaceholder: "Эҙләү...",
favoritePlaceholder: "Фаворит исеме",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Ҡала исеме",
languageDisplay: "Башҡортса",
maxFavoritesAlert: "Фавориттарҙың максималь санынан артыҡ!",
invalidUrlAlert: "Зинһар, дөрөҫ URL керетегеҙ (миҫал: https://example.com).",
voiceSearchNotSupported: "Тавышлы эҙләү һеҙҙең браузерҙа ҡулланылмай. Текст эҙләүен ҡулланығыҙ.",
weatherError: "Һава торошо мәғлүмәттәре йөкләнмәне.",
personalization: "Шәхсиләштереү",
shortcuts: "Клавиатура Кыҫҡа Юлдары",
searchShortcut: "Эҙләү Чыбығы:",
favoriteShortcut: "Фаворит Өҫтәү:",
settingsShortcut: "Көйләү Панеле:",
historyShortcut: "Тарих Панеле:",
imagesShortcut: "Рәсем Эҙләүе:",
shoppingShortcut: "Һатыу Эҙләүе:",
newsShortcut: "Яңылыҡ Эҙләүе:",
searchHistory: "Эҙләү Тарихы",
clearHistory: "Тарихты Тазалау",
noHistory: "Эҙләү тарихы юҡ.",
account: "Хисап",
login: "Кереү",
register: "Теркәлеү",
logout: "Сығу",
welcome: "Рәхим итегеҙ",
usernamePlaceholder: "Ҡулланыусы исеме",
passwordPlaceholder: "Пароль",
accountTitle: "Хисап",
accountLogin: "Хисап (Кереү өсөн баҫығыҙ)",
accountLoggedIn: "Хисап (Сығу өсөн баҫығыҙ)",
accountError: "Дөрөҫ булмаған ҡулланыусы исеме йәки пароль.",
usernameTooShort: "Ҡулланыусы исеме кәмендә 2 символдан торорға тиеш.",
passwordTooShort: "Пароль кәмендә 4 символдан торорға тиеш.",
usernameTaken: "Был ҡулланыусы исеме инде алынған.",
confirm: "Яҡшы",
cancel: "Кире ҡайтарыу",
voiceSearch: "Әйткәндәрегеҙ бында күренәсәк...",
  aiProvider: "AI Тәэмин Итүче:",
    customAiUrl: "Махсус AI URL:",
    showAISearch: "AI Эҙләүне Күрһәтеү:",
    aiShortcut: "AI Эҙләү:",
    accountIcon: "Хисап Иконкаһы",
    weather: "Һава",
    weatherApi: "Һава API",
    openWeatherMapApiKey: "OpenWeatherMap API Ключы",
    visualCrossingApiKey: "Visual Crossing API Ключы",
    weatherApiKey: "Һава API Ключы:",
    aiSearch: "AI Эҙләү",
    settings: "Баптаулар",
    history: "Тарых",
    weatherLoading: "Жүктөлүүдө...",
    weatherError: "Аба ырайы алынган жок",
    weatherLocationEmpty: "Сураныч, бир жайгашууну киргизиңиз",
    weatherApiKeyMissing: "API ачкычы жетишпейт",
    weatherClear: "Ачык",
    weatherPartlyCloudy: "Кысмен булуттуу",
    weatherCloudy: "Булуттуу",
    weatherRain: "Жамгыр",
    weatherSnow: "Кар",
    weatherWindy: "Шамалдуу",
    weatherFog: "Туман",
    weatherShower: "Жамгыр",
    weatherLightRain: "Жеңил жамгыр",
        loading: "Жүктөлүүдө...",
        noLocation: "Жайгашуу киргизилген жок",
        youtubeError: "YouTube видеосу жүктөлгөн жок",
        resetConfirm: "Бардык жөндөөлөрдү жана маалыматтарды нөлдөп салууга ишенесизби?",
        resetSuccess: "Браузер ийгиликтүү нөлдөндү!"
},
ug: {
bgUrl: "تەگلىك URL:",
font: "خەت:",
theme: "رەڭ تېمىسى:",
accentColor: "ئەسەرلىك رەڭ:",
language: "تىل:",
logoDisplay: "لوقو كۆرۈنۈشى:",
system: "سىستېما",
searchEngine: "ئىزدەش ماتورى:",
showFavorites: "ياخشى كۆرگەنلەرنى كۆرسەت:",
maxFavorites: "ياخشى كۆرگەنلەرنىڭ ئەڭ يۇقىرى سانى:",
showSuggestions: "ئىزدەش تەكلىپلىرىنى كۆرسەت:",
showWeather: "ھاۋا رايىنى كۆرسەت:",
weatherLocation: "ھاۋا رايى جايى:",
showInfoBar: "ئۇچۇر بالداقىنى كۆرسەت:",
weatherUpdateInterval: "ھاۋا رايى يېڭىلاش ئارىلىقى:",
linkBehavior: "ئۇلانما ھەرىكىتى:",
apply: "قوللاش",
favoriteName: "ئاتى:",
favoriteUrl: "URL:",
add: "قوش",
search: "ئىزدە",
images: "سۈرەتلەر",
shopping: "سېتىۋېلىش",
news: "خەۋەرلەر",
addFavorite: " + ",
dark: "قاراڭغۇ",
light: "يورۇق",

logoOnly: "پەقەت لوقو",
logoAndName: "لوقو ۋە ئات",
none: "ھېچنېمە",
yes: "ھەئە",
no: "ياق",
every5Min: "ھەر 5 مىنۇتتا",
every10Min: "ھەر 10 مىنۇتتا",
every30Min: "ھەر 30 مىنۇتتا",
manual: "قولدا",
newTab: "يېڭى بەتتە ئاچ",
closeCurrent: "نۆۋەتتىكى بەتنى ياپ",
searchPlaceholder: "ئىزدە...",
favoritePlaceholder: "ياخشى كۆرگەن ئاتى",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "شەھەر ئاتى",
languageDisplay: "ئۇيغۇرچە",
maxFavoritesAlert: "ياخشى كۆرگەنلەرنىڭ ئەڭ يۇقىرى سانىغا يەتتى!",
invalidUrlAlert: "توغرا URL كىرگۈزۈڭ (مەسىلەن: https://example.com).",
voiceSearchNotSupported: "ئاۋازلىق ئىزدەش توركۆرگۈچىڭىزدا قوللىنمايدۇ. تېكىست ئىزدەشنى ئىشلەت.",
weatherError: "ھاۋا رايى ئۇچۇرلىرى يۈكلەنمىدى.",
personalization: "شەخسىيلەشتۈرۈش",
shortcuts: "تاختا كونۇپكا قىسقا يوللىرى",
searchShortcut: "ئىزدەش قۇرچىسى:",
favoriteShortcut: "ياخشى كۆرگەن قوش:",
settingsShortcut: "تەڭشەك پانېلى:",
historyShortcut: "تارىخ پانېلى:",
imagesShortcut: "سۈرەت ئىزدەش:",
shoppingShortcut: "سېتىۋېلىش ئىزدەش:",
newsShortcut: "خەۋەر ئىزدەش:",
searchHistory: "ئىزدەش تارىخى",
clearHistory: "تارىخنى تازىلاش",
noHistory: "ئىزدەش تارىخى يوق.",
account: "ھېساب",
login: "كېرگۈزۈش",
register: "تېگىشلىك",
logout: "چىقىش",
welcome: "خۇش كەلدىڭىز",
usernamePlaceholder: "ئادەم نامى",
passwordPlaceholder: "پارول",
accountTitle: "ھېساب",
accountLogin: "ھېساب (كېرگۈزۈش ئۈچۈن بېسىڭ)",
accountLoggedIn: "ھېساب (چىقىش ئۈچۈن بېسىڭ)",
accountError: "ناتوغرا ئادەم نامى ياكى پارول.",
usernameTooShort: "ئادەم نامى كەم دېگەندە 2 بەلگىدىن تۇرۇشى كېرەك.",
passwordTooShort: "پارول كەم دېگەندە 4 بەلگىدىن تۇرۇشى كېرەك.",
usernameTaken: "بۇ ئادەم نامى ئالدىنلا ئېلىنغان.",
confirm: "رازى",
cancel: "قايتۇرۇش",
voiceSearch: "ئويلاپ باققانلىرىڭىز بۇ يەردە كۆرۈنىدۇ...",
    aiProvider: "AI تەمىنلىگۈچى:",
    customAiUrl: "ئالاھىدە AI URL:",
    showAISearch: "AI ئىزدەشنى كۆرسەت:",
    aiShortcut: "AI ئىزدەش:",
    accountIcon: "ھېساب سىنبەلگىسى",
    weather: "ھава",
    weatherApi: "ھава API",
    openWeatherMapApiKey: "OpenWeatherMap API كىلىتى",
    visualCrossingApiKey: "Visual Crossing API كىلىتى",
    weatherApiKey: "ھава API كىلىتى:",
    aiSearch: "AI ئىزدەش",
    settings: "بаптаулар",
    history: "تارخ",
    weatherLoading: "يۈكلەش...",
    weatherError: "ھاۋا رايى ئۇچۇرلىرى يۈكلەنمىدى.",
    weatherLocationEmpty: "سوراڭ، بىر جاي كىرگۈزۈڭ.",
    weatherApiKeyMissing: "API ئاچقۇچى يوق.",
    weatherClear: "ئاق",
    weatherPartlyCloudy: "بىر قىسىم بۇلۇت",
    weatherCloudy: "بۇلۇت",
    weatherRain: "ياغمۇ",
    weatherSnow: "قار",
    weatherWindy: "شامال",
    weatherFog: "تۇمان",
    weatherShower: "ياغما",
    weatherLightRain: "يېڭىل ياغما",
        loading: "يۈكلەش...",
        noLocation: "لطفا یک مکان وارد کنید",
        youtubeError: "ویدیوهای YouTube بارگذاری نشد",
        resetConfirm: "آیا مطمئن هستید که می‌خواهید تمام تنظیمات و داده‌ها را بازنشانی کنید؟",
        resetSuccess: "مرورگر با موفقیت بازنشانی شد!"
},
sah: {
bgUrl: "Фон URL:",
font: "Шрифт:",
theme: "Өҥ Темата:",
accentColor: "Акцент Өҥө:",
language: "Тыл:",
logoDisplay: "Логотип Көрдөрүү:",
system: "Система",
searchEngine: "Көрдөө Мотор:",
showFavorites: "Тааҕыннары Көрдөр:",
maxFavorites: "Тааҕыннар Максимальнай Числаһа:",
showSuggestions: "Көрдөө Суруллары Көрдөр:",
showWeather: "Күнү Көрдөр:",
weatherLocation: "Күн Ордуга:",
showInfoBar: "Информация Панелын Көрдөр:",
weatherUpdateInterval: "Күн Уларыта Аралыга:",
linkBehavior: "Сигэ Хамсааһына:",
apply: "Тутун",
favoriteName: "Аата:",
favoriteUrl: "URL:",
add: "Эп",
search: "Көрдөө",
images: "Ойуулар",
shopping: "Атыылааһын",
news: "Суһуохтар",
addFavorite: " + ",
dark: "Хараҥа",
light: "Сүүрэ",
logoOnly: "Логотип эрэ",
logoAndName: "Логотип уонна Аата",
none: "Суох",
yes: "Сөп",
no: "Суох",
every5Min: "Бүтүн 5 мүнүүтэ",
every10Min: "Бүтүн 10 мүнүүтэ",
every30Min: "Бүтүн 30 мүнүүтэ",
manual: "Илии нөҥүө",
newTab: "Саҥа Таба Аһыы",
closeCurrent: "Билигинни Таба Эрэ Ябуу",
searchPlaceholder: "Көрдөө...",
favoritePlaceholder: "Тааҕын аата",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Куорат аата",
languageDisplay: "Саха тыла",
maxFavoritesAlert: "Тааҕыннар максимальнай числаларын аастыбыт!",
invalidUrlAlert: "Дууһа, дьоҕус URL киллэр (мисал: https://example.com).",
voiceSearchNotSupported: "Сүүһү көрдөө браузерга колдоого алынбайт. Текст көрдөөтү колдон.",
weatherError: "Күн информацията киллэриллэ баттаах.",
personalization: "Шахсылааһын",
shortcuts: "Клавиатура Кыра Юллара",
searchShortcut: "Көрдөө Чыыһыла:",
favoriteShortcut: "Тааҕын Эп:",
settingsShortcut: "Суруйуу Панела:",
historyShortcut: "Туохтара Панела:",
imagesShortcut: "Ойуу Көрдөө:",
shoppingShortcut: "Атыылааһын Көрдөө:",
newsShortcut: "Суһуох Көрдөө:",
searchHistory: "Көрдөө Туохтара",
clearHistory: "Туохтары Тазар",
noHistory: "Көрдөө туохтара суох.",
account: "Учетная запись",
login: "Киир",
register: "Регистрациялаа",
logout: "Таҕыс",
welcome: "Кэлэр",
usernamePlaceholder: "Кыттааччы аата",
passwordPlaceholder: "Киирэргэ",
accountTitle: "Учетная запись",
accountLogin: "Учетная запись (Киирэрга баттаа)",
accountLoggedIn: "Учетная запись (Таҕысарга баттаа)",
accountError: "Сатанар кыттааччы аата эбэки киирэргэ.",
usernameTooShort: "Кыттааччы аата саамай кырата 2 сиимбэллээх буолуохтаах.",
passwordTooShort: "Киирэргэ саамай кырата 4 сиимбэллээх буолуохтаах.",
usernameTaken: "Бу кыттааччы аата инниккэ ылыллыбыт.",
confirm: "Сөп",
cancel: "Салҕаа",
voiceSearch: "Эппиттэриҥ бу илик көрүөт...",
    aiProvider: "AI Провайдер:",
    customAiUrl: "Аналлаах AI URL:",
    showAISearch: "AI Көрдөөтү Көрдөр:",
    aiShortcut: "AI Көрдөө:",
    accountIcon: "Учетная запись иконката",
    weather: "Ауа-райы",
    weatherApi: "Ауа-райы API",
    openWeatherMapApiKey: "OpenWeatherMap API Кілті",
    visualCrossingApiKey: "Visual Crossing API Кілті",
    weatherApiKey: "Ауа-райы API Кілті:",
    aiSearch: "AI Издөө",
    settings: "Баптаулар",
    history: "Тарых",
    weatherLoading: "Жүктөлүүдө...",
    weatherError: "Аба ырайы алынган жок",
    weatherLocationEmpty: "Сураныч, бир жайгашууну киргизиңиз",
    weatherApiKeyMissing: "API ачкычы жетишпейт",
    weatherClear: "Ачык",
    weatherPartlyCloudy: "Кысмен булуттуу",
    weatherCloudy: "Булуттуу",
    weatherRain: "Жамгыр",
    weatherSnow: "Кар",
    weatherWindy: "Шамалдуу",
    weatherFog: "Туман",
    weatherShower: "Жамгыр",
    weatherLightRain: "Жеңил жамгыр",
        loading: "Жүктөлүүдө...",
        noLocation: "Жайгашуу киргизилген жок",
        youtubeError: "YouTube видеосу жүктөлгөн жок",
        resetConfirm: "Бардык жөндөөлөрдү жана маалыматтарды нөлдөп салууга ишенесизби?",
        resetSuccess: "Браузер ийгиликтүү нөлдөндү!"
},
cv: {
bgUrl: "Фон URL:",
font: "Хӗр:",
theme: "Тӗс Теми:",
accentColor: "Акцент Тӗсӗ:",
language: "Чӗлхе:",
logoDisplay: "Логотип Кӑтартни:",
system: "Система",
searchEngine: "Ҫӗрле Мотор:",
showFavorites: "Фаворитсене Кӑтарт:",
maxFavorites: "Фаворитсен Максимал Сани:",
showSuggestions: "Ҫӗрле Тӑвӑлсеме Кӑтарт:",
showWeather: "Хыват Кӑтарт:",
weatherLocation: "Хыват Урӑхӗ:",
showInfoBar: "Мӑшӑр Панелӗне Кӑтарт:",
weatherUpdateInterval: "Хыват Ятӑшар Араслихӗ:",
linkBehavior: "Сылтама Хӑвӑрлихӗ:",
apply: "Тӑпшӑна",
favoriteName: "Ат:",
favoriteUrl: "URL:",
add: "Ҫӳт",
search: "Ҫӗрле",
images: "Риссем",
shopping: "Сӑтӑрлих",
news: "Ятӑшӑвсем",
addFavorite: " + ",
dark: "Кӑра",
light: "Ҫӗр",
logoOnly: "Тек Логотип",
logoAndName: "Логотип Пӑхӑҫ Ат",
none: "Вӗҫӗ",
yes: "Эйе",
no: "Йӑвӑш",
every5Min: "Хурал 5 мӗнкӗ",
every10Min: "Хурал 10 мӗнкӗ",
every30Min: "Хурал 30 мӗнкӗ",
manual: "Ҫул Таҫтӑн",
newTab: "Ятӑ Пӑштакӑ Аҫӑ",
closeCurrent: "Ҫӑкӑн Пӑштакӑ Пӑхӑ",
searchPlaceholder: "Ҫӗрле...",
favoritePlaceholder: "Фаворит ат",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Шӑхӗр ат",
languageDisplay: "Чӑвашла",
maxFavoritesAlert: "Фаворитсен максимал сани ашты!",
invalidUrlAlert: "Зарӑ, тӳрӗ URL кӗрт (мисал: https://example.com).",
voiceSearchNotSupported: "Тавӑрлих ҫӗрле сӑн браузерӗнче тӗрлешмей. Текст ҫӗрле тӑпшӑна.",
weatherError: "Хыват мӑшӑрӗ ҫӳккӗ ҫук.",
personalization: "Шӑхсилесси",
shortcuts: "Клавиатура Кӑҫӑ Юлта",
searchShortcut: "Ҫӗрле Ҫӗрӗ:",
favoriteShortcut: "Фаворит Ҫӳт:",
settingsShortcut: "Кӑтартма Панеле:",
historyShortcut: "Тарих Панеле:",
imagesShortcut: "Рис Ҫӗрле:",
shoppingShortcut: "Сӑтӑрлих Ҫӗрле:",
newsShortcut: "Ятӑшӑв Ҫӗрле:",
searchHistory: "Ҫӗрле Тарихӗ",
clearHistory: "Тарихӗ Таҫаланӑ",
noHistory: "Ҫӗрле тарихӗ юк.",
account: "Хуҫа",
login: "Кир",
register: "Регистраци",
logout: "Чык",
welcome: "Кил",
usernamePlaceholder: "Кулланучы ат",
passwordPlaceholder: "Пароль",
accountTitle: "Хуҫа",
accountLogin: "Хуҫа (Кир тӳле)",
accountLoggedIn: "Хуҫа (Чык тӳле)",
accountError: "Ярӑмлӑ кулланучы ат йӑва пароль.",
usernameTooShort: "Кулланучы ат кӗмне 2 харптан турумалла.",
passwordTooShort: "Пароль кӗмне 4 харптан турумалла.",
usernameTaken: "Пу кулланучы ат инче алнӑ.",
confirm: "Яр",
cancel: "Итлем",
voiceSearch: "Сказанны здесь пӑхӑнчӗк...",
   aiProvider: "AI Провайдер:",
    customAiUrl: "Махсус AI URL:",
    showAISearch: "AI Ҫӗрлени Кӑтарт:",
    aiShortcut: "AI Ҫӗрле:",
    accountIcon: "Хуҫа Иконка",
    weather: "Ауа-райы",
    weatherApi: "Ауа-райы API",
    openWeatherMapApiKey: "OpenWeatherMap API Кілті",
    visualCrossingApiKey: "Visual Crossing API Кілті",
    weatherApiKey: "Ауа-райы API Кілті:",
    aiSearch: "AI Издөө",
    settings: "Баптаулар",
    history: "Тарых",
    weatherLoading: "Жүктөлүүдө...",
    weatherError: "Аба ырайы алынган жок",
    weatherLocationEmpty: "Сураныч, бир жайгашууну киргизиңиз",
    weatherApiKeyMissing: "API ачкычы жетишпейт",
    weatherClear: "Ачык",
    weatherPartlyCloudy: "Кысмен булуттуу",
    weatherCloudy: "Булуттуу",
    weatherRain: "Жамгыр",
    weatherSnow: "Кар",
    weatherWindy: "Шамалдуу",
    weatherFog: "Туман",
    weatherShower: "Жамгыр",
    weatherLightRain: "Жеңил жамгыр",
        loading: "Жүктөлүүдө...",
        noLocation: "Жайгашуу киргизилген жок",
        youtubeError: "YouTube видеосу жүктөлгөн жок",
        resetConfirm: "Бардык жөндөөлөрдү жана маалыматтарды нөлдөп салууга ишенесизби?",
        resetSuccess: "Браузер ийгиликтүү нөлдөндү!"
},
gag: {
bgUrl: "Arka Plan URL:",
font: "Harf:",
theme: "Renk Teması:",
accentColor: "Vurgu Renk:",
language: "Dil:",
logoDisplay: "Logo Görünüşü:",
system: "Sistem",
searchEngine: "Axtarma Motoru:",
showFavorites: "Favoritlari Göster:",
maxFavorites: "Favoritlarnin Maksimum Sayisi:",
showSuggestions: "Axtarma Tekliflerini Göster:",
showWeather: "Hava Durumini Göster:",
weatherLocation: "Hava Yeri:",
showInfoBar: "Bilgi Panelini Göster:",
weatherUpdateInterval: "Hava Yenileme Araligi:",
linkBehavior: "Baglantu Davranişi:",
apply: "Uygula",
favoriteName: "Adi:",
favoriteUrl: "URL:",
add: "Ekle",
search: "Axtar",
images: "Resimler",
shopping: "Alışveriş",
news: "Haberler",
addFavorite: " + ",
dark: "Kara",
light: "Açıq",
logoOnly: "Yalnız Logo",
logoAndName: "Logo ve Ad",
none: "Hiçbiri",
yes: "Evet",
no: "Hayır",
every5Min: "Her 5 Dakika",
every10Min: "Her 10 Dakika",
every30Min: "Her 30 Dakika",
manual: "El ile",
newTab: "Yeni Sekmede Aç",
closeCurrent: "Cari Sayfayi Kapat",
searchPlaceholder: "Axtar...",
favoritePlaceholder: "Favorit adi",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Şehir adi",
languageDisplay: "Gagauz",
maxFavoritesAlert: "Favoritlarnin maksimum sayisina yetişdi!",
invalidUrlAlert: "Lütfen doğru bir URL giriniz (örneğin: https://example.com).",
voiceSearchNotSupported: "Sesli axtarma tarayicinizda desteklenmir. Lütfen metin axtarmasini kullanin.",
weatherError: "Hava durumu yüklenmedi.",
personalization: "Kişiselleştirme",
shortcuts: "Klaviature Kisa Yolları",
searchShortcut: "Axtarma Çubuği:",
favoriteShortcut: "Favorit Ekle:",
settingsShortcut: "Ayarlar Paneli:",
historyShortcut: "Geçmiş Paneli:",
imagesShortcut: "Resim Axtarmasi:",
shoppingShortcut: "Alışveriş Axtarmasi:",
newsShortcut: "Haber Axtarmasi:",
searchHistory: "Axtarma Geçmişi",
clearHistory: "Geçmişi Temizle",
noHistory: "Axtarma geçmişi yox.",
account: "Hesap",
login: "Giriş yap",
register: "Kaydol",
logout: "Çıkış yap",
welcome: "Hoş geldin",
usernamePlaceholder: "Kullanıcı adı",
passwordPlaceholder: "Şifre",
accountTitle: "Hesap",
accountLogin: "Hesap (Giriş için tıkla)",
accountLoggedIn: "Hesap (Çıkış için tıkla)",
accountError: "Yanlış kullanıcı adı veya şifre.",
usernameTooShort: "Kullanıcı adı en az 2 karakter olmalı.",
passwordTooShort: "Şifre en az 4 karakter olmalı.",
usernameTaken: "Bu kullanıcı adı zaten alınmış.",
confirm: "Tamam",
cancel: "İptal",
voiceSearch: "Söyledikleriniz burada görünecek...",
   aiProvider: "AI Sağlayıcı:",
    customAiUrl: "Özel AI URL:",
    showAISearch: "AI Axtarışını Göster:",
    aiShortcut: "AI Axtarma:",
    accountIcon: "Hesap İkonu",
    weather: "Hava",
    weatherApi: "Hava API",
    openWeatherMapApiKey: "OpenWeatherMap API Anahtarı",
    visualCrossingApiKey: "Visual Crossing API Anahtarı",
    weatherApiKey: "Hava API Anahtarı:",
    aiSearch: "AI Arama",
    settings: "Ayarlar",
    history: "Geçmiş",
    weatherLoading: "Yükleniyor...",
    weatherError: "Hava durumu alınamadı",
    weatherLocationEmpty: "Lütfen bir konum girin",
    weatherApiKeyMissing: "API anahtarı eksik",
    aiProvider: "AI Sağlayıcı:",
    customAiUrl: "Özel AI URL:",
    showAISearch: "AI Axtarışını Göster:",
    aiShortcut: "AI Axtarma:",
    accountIcon: "Hesap İkonu",
    weather: "Hava",
    weatherApi: "Hava API",
    openWeatherMapApiKey: "OpenWeatherMap API Anahtarı",
    visualCrossingApiKey: "Visual Crossing API Anahtarı",
    weatherApiKey: "Hava API Anahtarı:",
    aiSearch: "AI Arama",
    settings: "Ayarlar",
    history: "Geçmiş",
    weatherLoading: "Yükleniyor...",
    weatherError: "Hava durumu alınamadı",
    weatherLocationEmpty: "Lütfen bir konum girin",
    weatherApiKeyMissing: "API anahtarı eksik",
    weatherClear: "Açık",
    weatherPartlyCloudy: "Kısmen Bulutlu",
    weatherCloudy: "Bulutlu",
    weatherRain: "Yağmur",
    weatherSnow: "Kar",
    weatherWindy: "Rüzgarlı",
    weatherFog: "Sisli",
    weatherShower: "Sağanak",
    weatherLightRain: "Hafif Yağmur",
    loading: "Yükleniyor...",
    weatherError: "Hava durumu alınamadı",
    noLocation: "Lütfen bir konum girin",
    youtubeError: "YouTube videosu yüklenemedi",
    resetConfirm: "Tüm ayarları ve verileri sıfırlamak istediğinize emin misiniz?",
    resetSuccess: "Sıfırlama başarılı!",
    noWallpapers: "Hiç duvar kağıdı yok."

},
  en: {
    bgUrl: "Background URL:",
    font: "Font:",
    theme: "Color Theme:",
    accentColor: "Accent Color:",
    language: "Language:",
    logoDisplay: "Logo Display:",
    system: "System",
    searchEngine: "Search Engine:",
    showFavorites: "Show Favorites:",
    maxFavorites: "Maximum Favorites:",
    showSuggestions: "Show Search Suggestions:",
    showWeather: "Show Weather:",
    weatherLocation: "Weather Location:",
    showInfoBar: "Show Info Bar:",
    weatherUpdateInterval: "Weather Update Frequency:",
    linkBehavior: "Link Behavior:",
    apply: "Apply",
    favoriteName: "Name:",
    favoriteUrl: "URL:",
    add: "Add",
    search: "Search",
    images: "Images",
    shopping: "Shopping",
    news: "News",
    addFavorite: " + ",
    dark: "Dark",
    light: "Light",
    logoOnly: "Logo Only",
    logoAndName: "Logo and Name",
    none: "None",
    yes: "Yes",
    no: "No",
    every5Min: "Every 5 Minutes",
    every10Min: "Every 10 Minutes",
    every30Min: "Every 30 Minutes",
    manual: "Manual",
    newTab: "Open in New Tab",
    closeCurrent: "Close This Page",
    searchPlaceholder: "Search...",
    favoritePlaceholder: "Favorite name",
    urlPlaceholder: "https://...",
    weatherLocationPlaceholder: "City name",
    languageDisplay: "English",
    maxFavoritesAlert: "Maximum number of favorites reached!",
    invalidUrlAlert: "Enter a valid URL (e.g., https://example.com).",
    voiceSearchNotSupported: "Voice search is not supported in your browser. Please use text search.",
    weatherError: "Failed to load weather.",
    personalization: "Personalization",
    shortcuts: "Keyboard Shortcuts",
    searchShortcut: "Search Bar:",
    favoriteShortcut: "Add Favorite:",
    settingsShortcut: "Settings Panel:",
    historyShortcut: "History Panel:",
    imagesShortcut: "Images Search:",
    shoppingShortcut: "Shopping Search:",
    newsShortcut: "News Search:",
    searchHistory: "Search History",
    clearHistory: "Clear History",
    noHistory: "No search history.",
    account: "Account",
    login: "Log In",
    register: "Register",
    logout: "Log Out",
    welcome: "Welcome",
    usernamePlaceholder: "Username",
    passwordPlaceholder: "Password",
    accountTitle: "Account",
    accountLogin: "Account (Click to log in)",
    accountLoggedIn: "Account (Click to log out)",
    accountError: "Incorrect username or password.",
    usernameTooShort: "Username must be at least 2 characters.",
    passwordTooShort: "Password must be at least 4 characters.",
    usernameTaken: "This username is already taken.",
    confirm: "OK",
    cancel: "Cancel",
    voiceSearch: "Your speech will appear here...",
    aiProvider: "AI Provider:",
    customAiUrl: "Custom AI URL:",
    showAISearch: "Show AI Search:",
    aiShortcut: "AI Search Shortcut:",
    aiSearch: "AI Search",
    accountIcon: "Account Icon",
    weather: "Weather",
    weatherApi: "Weather API",
    openWeatherMapApiKey: "OpenWeatherMap API Key:",
    visualCrossingApiKey: "Visual Crossing API Key:",
    weatherApiKey: "Weather API Key:",
    settings: "Settings",
    history: "History",
    loading: "Loading...",
    weatherLocationEmpty: "Please enter a location.",
    weatherApiKeyMissing: "API key is missing.",
    weatherClear: "Clear",
    weatherPartlyCloudy: "Partly Cloudy",
    weatherCloudy: "Cloudy",
    weatherRain: "Rain",
    weatherSnow: "Snow",
    weatherWindy: "Windy",
    weatherFog: "Fog",
    weatherShower: "Shower",
    weatherLightRain: "Light Rain",
    noLocation: "Please enter a location.",
    youtubeError: "YouTube video could not be loaded.",
    resetConfirm: "Are you sure you want to reset all settings and data?",
    resetSuccess: "Successfully reset!",
    noWallpapers: "No wallpapers found."
  },
es: {
bgUrl: "URL de Fondo:",
font: "Fuente:",
theme: "Tema de Color:",
accentColor: "Color de Acento:",
language: "Idioma:",
logoDisplay: "Visualización del Logotipo:",
system: "Sistema",
searchEngine: "Motor de Búsqueda:",
showFavorites: "Mostrar Favoritos:",
maxFavorites: "Número Máximo de Favoritos:",
showSuggestions: "Mostrar Sugerencias de Búsqueda:",
showWeather: "Mostrar Clima:",
weatherLocation: "Ubicación del Clima:",
showInfoBar: "Mostrar Barra de Información:",
weatherUpdateInterval: "Frecuencia de Actualización del Clima:",
linkBehavior: "Comportamiento del Enlace:",
apply: "Aplicar",
favoriteName: "Nombre:",
favoriteUrl: "URL:",
add: "Añadir",
search: "Buscar",
images: "Imágenes",
shopping: "Compras",
news: "Noticias",
addFavorite: " + ",
dark: "Oscuro",
light: "Claro",
logoOnly: "Solo Logotipo",
logoAndName: "Logotipo y Nombre",
none: "Ninguno",
yes: "Sí",
no: "No",
every5Min: "Cada 5 Minutos",
every10Min: "Cada 10 Minutos",
every30Min: "Cada 30 Minutos",
manual: "Manual",
newTab: "Abrir en Nueva Pestaña",
closeCurrent: "Cerrar Esta Página",
searchPlaceholder: "Buscar...",
favoritePlaceholder: "Nombre del favorito",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Nombre de la ciudad",
languageDisplay: "Español",
maxFavoritesAlert: "¡Se alcanzó el número máximo de favoritos!",
invalidUrlAlert: "Ingrese una URL válida (por ejemplo, https://example.com).",
voiceSearchNotSupported: "La búsqueda por voz no es compatible con su navegador. Utilice la búsqueda de texto.",
weatherError: "No se pudo cargar el clima.",
personalization: "Personalización",
shortcuts: "Atajos de Teclado",
searchShortcut: "Barra de Búsqueda:",
favoriteShortcut: "Añadir Favorito:",
settingsShortcut: "Panel de Configuración:",
historyShortcut: "Panel de Historial:",
imagesShortcut: "Búsqueda de Imágenes:",
shoppingShortcut: "Búsqueda de Compras:",
newsShortcut: "Búsqueda de Noticias:",
searchHistory: "Historial de Búsqueda",
clearHistory: "Borrar Historial",
noHistory: "No hay historial de búsqueda.",
account: "Cuenta",
login: "Iniciar sesión",
register: "Registrarse",
logout: "Cerrar sesión",
welcome: "Bienvenido",
usernamePlaceholder: "Nombre de usuario",
passwordPlaceholder: "Contraseña",
accountTitle: "Cuenta",
accountLogin: "Cuenta (Haz clic para iniciar sesión)",
accountLoggedIn: "Cuenta (Haz clic para cerrar sesión)",
accountError: "Nombre de usuario o contraseña incorrectos.",
usernameTooShort: "El nombre de usuario debe tener al menos 2 caracteres.",
passwordTooShort: "La contraseña debe tener al menos 4 caracteres.",
usernameTaken: "Este nombre de usuario ya está tomado.",
confirm: "Aceptar",
cancel: "Cancelar",
voiceSearch: "Lo que digas aparecerá aquí...",
   aiProvider: "Proveedor de IA:",
    customAiUrl: "URL de IA personalizada:",
    showAISearch: "Mostrar búsqueda de IA:",
    aiShortcut: "Búsqueda de IA:",
    accountIcon: "Icono de cuenta",
    weather: "Clima:",
    weatherApi: "API de Clima:",
    openWeatherMapApiKey: "Clave API de OpenWeatherMap:",
    visualCrossingApiKey: "Clave API de Visual Crossing:",
    weatherApiKey: "Clave API de Clima:",
    aiSearch: "Búsqueda de IA",
    settings: "Configuración",
    history: "Historial",
    weatherLoading: "Cargando...",
    weatherLocationEmpty: "Por favor, ingrese una ubicación",
    weatherApiKeyMissing: "Falta la clave API",
    weatherError: "No se pudo obtener la información del clima.",
    weatherLocationEmpty: "Por favor, ingrese una ubicación",
    weatherApiKeyMissing: "Falta la clave API",
    weatherClear: "Despejado",
    weatherPartlyCloudy: "Parcialmente nublado",
    weatherCloudy: "Nublado",
    weatherRain: "Lluvia",
    weatherSnow: "Nieve",
    weatherWindy: "Ventoso",
    weatherFog: "Niebla",
    weatherShower: "Chubasco",
    weatherLightRain: "Lluvia ligera",
    weatherError: "No se pudo obtener la información del clima.",
        loading: "Cargando...",
        noLocation: "Por favor, ingrese una ubicación",
        youtubeError: "No se pudo cargar el video de YouTube",
        resetConfirm: "¿Está seguro de que desea restablecer todas las configuraciones y datos?",
        resetSuccess: "¡El navegador se ha restablecido con éxito!"
},
jp: {
bgUrl: "背景URL:",
font: "フォント:",
theme: "テーマ:",
accentColor: "アクセントカラー:",
language: "言語:",
logoDisplay: "ロゴ表示:",
system: "システム",
searchEngine: "検索エンジン:",
showFavorites: "お気に入りを表示:",
maxFavorites: "お気に入りの最大数:",
showSuggestions: "検索候補を表示:",
showWeather: "天気を表示:",
weatherLocation: "天気場所:",
showInfoBar: "情報バーを表示:",
weatherUpdateInterval: "天気更新間隔:",
linkBehavior: "リンク動作:",
apply: "適用",
favoriteName: "名前:",
favoriteUrl: "URL:",
add: "追加",
search: "検索",
images: "画像",
shopping: "ショッピング",
news: "ニュース",
addFavorite: " + ",
dark: "ダーク",
light: "ライト",
logoOnly: "ロゴのみ",
logoAndName: "ロゴと名前",
none: "なし",
yes: "はい",
no: "いいえ",
every5Min: "5分毎",
every10Min: "10分毎",
every30Min: "30分毎",
manual: "手動",
newTab: "新しいタブで開く",
closeCurrent: "現在のページを閉じる",
searchPlaceholder: "検索...",
favoritePlaceholder: "お気に入りの名前",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "都市名",
languageDisplay: "日本語",
maxFavoritesAlert: "お気に入りの最大数に達しました！",
invalidUrlAlert: "有効なURLを入力してください (例: https://example.com)。",
voiceSearchNotSupported: "音声検索はあなたのブラウザでサポートされていません。テキスト検索を使用してください。",
weatherError: "天気情報を取得できませんでした。",
personalization: "パーソナライズ",
shortcuts: "キーボードショートカット",
searchShortcut: "検索バー:",
favoriteShortcut: "お気に入り追加:",
settingsShortcut: "設定パネル:",
historyShortcut: "履歴パネル:",
imagesShortcut: "画像検索:",
shoppingShortcut: "ショッピング検索:",
newsShortcut: "ニュース検索:",
searchHistory: "検索履歴",
clearHistory: "履歴をクリア",
noHistory: "検索履歴がありません。",
account: "アカウント",
login: "ログイン",
register: "登録",
logout: "ログアウト",
welcome: "ようこそ",
usernamePlaceholder: "ユーザー名",
passwordPlaceholder: "パスワード",
accountTitle: "アカウント",
accountLogin: "アカウント (ログインするのにクリック)",
accountLoggedIn: "アカウント (ログアウトするのにクリック)",
accountError: "ユーザー名またはパスワードが正しくありません.",
usernameTooShort: "ユーザー名は少なくとも2文字以上でなければなりません.",
passwordTooShort: "パスワードは少なくとも4文字以上でなければなりません.",
usernameTaken: "このユーザー名はすでに取られています.",
confirm: "OK",
cancel: "キャンセル",
voiceSearch: "話した内容がここに表示されます...",
   aiProvider: "AI プロバイダー:",
    customAiUrl: "カスタム AI URL:",
    showAISearch: "AI 検索を表示:",
    aiShortcut: "AI 検索:",
    accountIcon: "アカウントアイコン",
    weather: "天気:",
    weatherApi: "天気 API:",
    openWeatherMapApiKey: "OpenWeatherMap API キー:",
    visualCrossingApiKey: "Visual Crossing API キー:",
    weatherApiKey: "天気 API キー:",
    aiSearch: "AI 検索",
    settings: "設定",
    history: "履歴",
    weatherLoading: "読み込み中...",
    weatherError: "天気情報を取得できませんでした",
    weatherLocationEmpty: "場所を入力してください",
    weatherApiKeyMissing: "APIキーがありません",
    weatherClear: "晴れ",
    weatherPartlyCloudy: "部分的に曇り",
    weatherCloudy: "曇り",
    weatherRain: "雨",
    weatherSnow: "雪",
    weatherWindy: "風",
    weatherFog: "霧",
    weatherShower: "シャワー",
    weatherLightRain: "小雨",
    weatherError: "天気情報を取得できませんでした",
    loading: "読み込み中...",
    noLocation: "場所を入力してください",
    weatherApiKeyMissing: "APIキーがありません",
    weatherClear: "晴れ",
    weatherPartlyCloudy: "部分的に曇り",
    weatherCloudy: "曇り",
    weatherRain: "雨",
    weatherSnow: "雪",
    weatherWindy: "風",
    weatherFog: "霧",
    weatherShower: "シャワー",
    weatherLightRain: "小雨",
    youtubeError: "YouTube動画を読み込めませんでした。",
    resetConfirm: "すべての設定とデータをリセットしてもよろしいですか？",
    resetSuccess: "ブラウザが正常にリセットされました！"

},
zh: {
bgUrl: "背景URL:",
font: "字体:",
theme: "主题:",
accentColor: "强调颜色:",
language: "语言:",
logoDisplay: "标志显示:",
system: "系统",
searchEngine: "搜索引擎:",
showFavorites: "显示收藏:",
maxFavorites: "最大收藏数:",
showSuggestions: "显示搜索建议:",
showWeather: "显示天气:",
weatherLocation: "天气位置:",
showInfoBar: "显示信息栏:",
weatherUpdateInterval: "天气更新间隔:",
linkBehavior: "链接行为:",
apply: "应用",
favoriteName: "名称:",
favoriteUrl: "URL:",
add: "添加",
search: "搜索",
images: "图片",
shopping: "购物",
news: "新闻",
addFavorite: " + ",
dark: "暗色",
light: "浅色",
logoOnly: "仅标志",
logoAndName: "标志和名称",
none: "无",
yes: "是",
no: "否",
every5Min: "每5分钟",
every10Min: "每10分钟",
every30Min: "每30分钟",
manual: "手动",
newTab: "在新标签页打开",
closeCurrent: "关闭当前页面",
searchPlaceholder: "搜索...",
favoritePlaceholder: "收藏名称",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "城市名称",
languageDisplay: "中文",
maxFavoritesAlert: "已达到最大收藏数！",
invalidUrlAlert: "请输入有效URL (例: https://example.com)。",
voiceSearchNotSupported: "您的浏览器不支持语音搜索。请使用文本搜索。",
weatherError: "无法加载天气信息。",
personalization: "个性化",
shortcuts: "键盘快捷键",
searchShortcut: "搜索栏:",
favoriteShortcut: "添加收藏:",
settingsShortcut: "设置面板:",
historyShortcut: "历史面板:",
imagesShortcut: "图片搜索:",
shoppingShortcut: "购物搜索:",
newsShortcut: "新闻搜索:",
searchHistory: "搜索历史",
clearHistory: "清除历史",
noHistory: "没有搜索历史。",
account: "账户",
login: "登录",
register: "注册",
logout: "登出",
welcome: "欢迎",
usernamePlaceholder: "用户名",
passwordPlaceholder: "密码",
accountTitle: "账户",
accountLogin: "账户 (点击登录)",
accountLoggedIn: "账户 (点击登出)",
accountError: "用户名或密码错误.",
usernameTooShort: "用户名至少2个字符.",
passwordTooShort: "密码至少4个字符.",
usernameTaken: "此用户名已被占用.",
confirm: "确定",
cancel: "取消",
voiceSearch: "您所说的话将在这里出现...",
   aiProvider: "AI 提供者:",
    customAiUrl: "自定义 AI URL:",
    showAISearch: "显示 AI 搜索:",
    aiShortcut: "AI 搜索:",
    accountIcon: "帐户图标",
    weather: "天气:",
    weatherApi: "天气 API:",
    openWeatherMapApiKey: "OpenWeatherMap API 密钥:",
    visualCrossingApiKey: "Visual Crossing API 密钥:",
    weatherApiKey: "天气 API 密钥:",
    aiSearch: "AI 搜索",
    settings: "设置",
    history: "历史",
    weatherLoading: "加载中...",
    weatherError: "无法获取天气信息",
    weatherLocationEmpty: "请输入位置",
    weatherApiKeyMissing: "缺少 API 密钥",
    weatherClear: "晴",
    weatherPartlyCloudy: "局部多云",
    weatherCloudy: "多云",
    weatherRain: "下雨",
    weatherSnow: "下雪",
    weatherWindy: "有风",
    weatherFog: "有雾",
    weatherShower: "阵雨",
    weatherLightRain: "小雨",
    weatherError: "无法获取天气信息",
    loading: "加载中...",
    noLocation: "请输入位置",
    weatherApiKeyMissing: "缺少 API 密钥",
    weatherClear: "晴",
    weatherPartlyCloudy: "局部多云",
    weatherCloudy: "多云",
    weatherRain: "下雨",
    weatherSnow: "下雪",
    weatherWindy: "有风",
    weatherFog: "有雾",
    weatherShower: "阵雨",
    weatherLightRain: "小雨",
    weatherError: "无法获取天气信息",
    loading: "加载中...",
    noLocation: "请输入位置",
    youtubeError: "无法加载YouTube视频。",
    resetConfirm: "您确定要重置所有设置和数据吗？",
    resetSuccess: "浏览器已成功重置！"
},
ko: {
bgUrl: "배경 URL:",
font: "글꼴:",
theme: "테마:",
accentColor: "강조 색상:",
language: "언어:",
logoDisplay: "로고 표시:",
system: "시스템",
searchEngine: "검색 엔진:",
showFavorites: "즐겨찾기 표시:",
maxFavorites: "최대 즐겨찾기 수:",
showSuggestions: "검색 제안 표시:",
showWeather: "날씨 표시:",
weatherLocation: "날씨 위치:",
showInfoBar: "정보 바 표시:",
weatherUpdateInterval: "날씨 업데이트 간격:",
linkBehavior: "링크 동작:",
apply: "적용",
favoriteName: "이름:",
favoriteUrl: "URL:",
add: "추가",
search: "검색",
images: "이미지",
shopping: "쇼핑",
news: "뉴스",
addFavorite: " + ",
dark: "다크",
light: "라이트",
logoOnly: "로고만",
logoAndName: "로고와 이름",
none: "없음",
yes: "예",
no: "아니오",
every5Min: "5분마다",
every10Min: "10분마다",
every30Min: "30분마다",
manual: "수동",
newTab: "새 탭에서 열기",
closeCurrent: "현재 페이지를 닫기",
searchPlaceholder: "검색...",
favoritePlaceholder: "즐겨찾기 이름",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "도시 이름",
languageDisplay: "한국어",
maxFavoritesAlert: "최대 즐겨찾기 수에 도달했습니다!",
invalidUrlAlert: "유효한 URL을 입력하세요 (예: https://example.com).",
voiceSearchNotSupported: "음성 검색은 브라우저에서 지원되지 않습니다. 텍스트 검색을 사용하세요.",
weatherError: "날씨 정보를 불러올 수 없습니다.",
personalization: "개인화",
shortcuts: "키보드 단축키",
searchShortcut: "검색 바:",
favoriteShortcut: "즐겨찾기 추가:",
settingsShortcut: "설정 패널:",
historyShortcut: "히스토리 패널:",
imagesShortcut: "이미지 검색:",
shoppingShortcut: "쇼핑 검색:",
newsShortcut: "뉴스 검색:",
searchHistory: "검색 기록",
clearHistory: "기록 지우기",
noHistory: "검색 기록이 없습니다.",
account: "계정",
login: "로그인",
register: "등록",
logout: "로그아웃",
welcome: "환영합니다",
usernamePlaceholder: "사용자 이름",
passwordPlaceholder: "비밀번호",
accountTitle: "계정",
accountLogin: "계정 (로그인하려면 클릭)",
accountLoggedIn: "계정 (로그아웃하려면 클릭)",
accountError: "잘못된 사용자 이름 또는 비밀번호.",
usernameTooShort: "사용자 이름은 최소 2자 이상이어야 합니다.",
passwordTooShort: "비밀번호는 최소 4자 이상이어야 합니다.",
usernameTaken: "이 사용자 이름은 이미 사용 중입니다.",
confirm: "확인",
cancel: "취소",
voiceSearch: "말한 내용이 여기 나타납니다...",
   aiProvider: "AI 제공자:",
    customAiUrl: "사용자 정의 AI URL:",
    showAISearch: "AI 검색 표시:",
    aiShortcut: "AI 검색:",
    accountIcon: "계정 아이콘",
    weather: "날씨:",
    weatherApi: "날씨 API:",
    openWeatherMapApiKey: "OpenWeatherMap API 키:",
    visualCrossingApiKey: "Visual Crossing API 키:",
    weatherApiKey: "날씨 API 키:",
    aiSearch: "AI 검색",
    settings: "설정",
    history: "히스토리",
    weatherLoading: "로딩 중...",
    weatherError: "날씨 정보를 가져올 수 없습니다.",
    weatherLocationEmpty: "위치를 입력해 주세요.",
    weatherApiKeyMissing: "API 키가 없습니다.",
    weatherClear: "맑음",
    weatherPartlyCloudy: "부분적으로 흐림",
    weatherCloudy: "흐림",
    weatherRain: "비",
    weatherSnow: "눈",
    weatherWindy: "바람",
    weatherFog: "안개",
    weatherShower: "소나기",
    weatherLightRain: "가벼운 비",
    weatherError: "날씨 정보를 가져올 수 없습니다.",
        loading: "로딩 중...",
        noLocation: "위치를 입력해 주세요.",
        youtubeError: "YouTube 동영상을 불러올 수 없습니다.",
        resetConfirm: "모든 설정과 데이터를 초기화하시겠습니까?",
        resetSuccess: "브라우저가 성공적으로 초기화되었습니다!"
},
de: {
bgUrl: "Hintergrund-URL:",
font: "Schriftart:",
theme: "Thema:",
accentColor: "Akzentfarbe:",
language: "Sprache:",
logoDisplay: "Logo-Anzeige:",
system: "System",
searchEngine: "Suchmaschine:",
showFavorites: "Favoriten anzeigen:",
maxFavorites: "Maximale Anzahl Favoriten:",
showSuggestions: "Suchvorschläge anzeigen:",
showWeather: "Wetter anzeigen:",
weatherLocation: "Wetterort:",
showInfoBar: "Infobalken anzeigen:",
weatherUpdateInterval: "Wetter-Aktualisierungsintervall:",
linkBehavior: "Link-Verhalten:",
apply: "Anwenden",
favoriteName: "Name:",
favoriteUrl: "URL:",
add: "Hinzufügen",
search: "Suchen",
images: "Bilder",
shopping: "Einkaufen",
news: "Nachrichten",
addFavorite: " + ",
dark: "Dunkel",
light: "Hell",
logoOnly: "Nur Logo",
logoAndName: "Logo und Name",
none: "Kein",
yes: "Ja",
no: "Nein",
every5Min: "Alle 5 Minuten",
every10Min: "Alle 10 Minuten",
every30Min: "Alle 30 Minuten",
manual: "Manuell",
newTab: "In neuem Tab öffnen",
closeCurrent: "Aktuelle Seite schließen",
searchPlaceholder: "Suchen...",
favoritePlaceholder: "Favoritenname",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Stadtname",
languageDisplay: "Deutsch",
maxFavoritesAlert: "Maximale Anzahl an Favoriten erreicht!",
invalidUrlAlert: "Bitte geben Sie eine gültige URL ein (z. B. https://example.com).",
voiceSearchNotSupported: "Die Sprachsuche wird von Ihrem Browser nicht unterstützt. Bitte verwenden Sie die Textsuche.",
weatherError: "Wetterinformationen konnten nicht geladen werden.",
personalization: "Personalisierung",
shortcuts: "Tastenkürzel",
searchShortcut: "Suchleiste:",
favoriteShortcut: "Favorit hinzufügen:",
settingsShortcut: "Einstellungen-Panel:",
historyShortcut: "Verlauf-Panel:",
imagesShortcut: "Bildersuche:",
shoppingShortcut: "Einkaufssuche:",
newsShortcut: "Nachrichtensuche:",
searchHistory: "Suchverlauf",
clearHistory: "Verlauf löschen",
noHistory: "Kein Suchverlauf vorhanden.",
account: "Konto",
login: "Anmelden",
register: "Registrieren",
logout: "Abmelden",
welcome: "Willkommen",
usernamePlaceholder: "Benutzername",
passwordPlaceholder: "Passwort",
accountTitle: "Konto",
accountLogin: "Konto (Klicken zum Anmelden)",
accountLoggedIn: "Konto (Klicken zum Abmelden)",
accountError: "Falscher Benutzername oder Passwort.",
usernameTooShort: "Benutzername muss mindestens 2 Zeichen lang sein.",
passwordTooShort: "Passwort muss mindestens 4 Zeichen lang sein.",
usernameTaken: "Dieser Benutzername ist bereits vergeben.",
confirm: "OK",
cancel: "Abbrechen",
voiceSearch: "Ihre gesprochenen Worte erscheinen hier...",
   aiProvider: "AI Anbieter:",
    customAiUrl: "Benutzerdefinierte AI URL:",
    showAISearch: "AI Suche anzeigen:",
    aiShortcut: "AI Suche:",
    accountIcon: "Konto Icon",
    weather: "Wetter:",
    weatherApi: "Wetter API:",
    openWeatherMapApiKey: "OpenWeatherMap API Schlüssel:",
    visualCrossingApiKey: "Visual Crossing API Schlüssel:",
    weatherApiKey: "Wetter API Schlüssel:",
    aiSearch: "AI Suche",
    settings: "Einstellungen",
    history: "Verlauf",
    weatherLoading: "Lädt...",
    weatherError: "Wetterinformationen konnten nicht abgerufen werden.",
    weatherLocationEmpty: "Bitte geben Sie einen Standort ein.",
    weatherApiKeyMissing: "API-Schlüssel fehlt.",
    weatherClear: "Klar",
    weatherPartlyCloudy: "Teilweise bewölkt",
    weatherCloudy: "Bewölkt",
    weatherRain: "Regnerisch",
    weatherSnow: "Schneebedeckt",
    weatherWindy: "Windig",
    weatherFog: "Nebelig",
    weatherShower: "Regenschauer",
    weatherLightRain: "Leichter Regen",
    weatherError: "Wetterinformationen konnten nicht abgerufen werden.",
        loading: "Lädt...",
        noLocation: "Bitte geben Sie einen Standort ein.",
        youtubeError: "YouTube-Video konnte nicht geladen werden.",
        resetConfirm: "Sind Sie sicher, dass Sie alle Einstellungen und Daten zurücksetzen möchten?",
        resetSuccess: "Browser erfolgreich zurückgesetzt!"
},
fr: {
bgUrl: "URL de l'arrière-plan:",
font: "Police:",
theme: "Thème:",
accentColor: "Couleur d'accent:",
language: "Langue:",
logoDisplay: "Affichage du logo:",
system: "Système",
searchEngine: "Moteur de recherche:",
showFavorites: "Afficher les favoris:",
maxFavorites: "Nombre maximum de favoris:",
showSuggestions: "Afficher les suggestions de recherche:",
showWeather: "Afficher la météo:",
weatherLocation: "Lieu de la météo:",
showInfoBar: "Afficher la barre d'information:",
weatherUpdateInterval: "Intervalle de mise à jour de la météo:",
linkBehavior: "Comportement des liens:",
apply: "Appliquer",
favoriteName: "Nom:",
favoriteUrl: "URL:",
add: "Ajouter",
search: "Rechercher",
images: "Images",
shopping: "Shopping",
news: "Actualités",
addFavorite: " + ",
dark: "Sombre",
light: "Clair",
logoOnly: "Seulement le logo",
logoAndName: "Logo et nom",
none: "Aucun",
yes: "Oui",
no: "Non",
every5Min: "Toutes les 5 minutes",
every10Min: "Toutes les 10 minutes",
every30Min: "Toutes les 30 minutes",
manual: "Manuel",
newTab: "Ouvrir dans un nouvel onglet",
closeCurrent: "Fermer la page actuelle",
searchPlaceholder: "Rechercher...",
favoritePlaceholder: "Nom du favori",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Nom de la ville",
languageDisplay: "Français",
maxFavoritesAlert: "Nombre maximum de favoris atteint !",
invalidUrlAlert: "Veuillez entrer une URL valide (ex: https://example.com).",
voiceSearchNotSupported: "La recherche vocale n'est pas prise en charge par votre navigateur. Utilisez la recherche par texte.",
weatherError: "Impossible de charger les informations météo.",
personalization: "Personnalisation",
shortcuts: "Raccourcis clavier",
searchShortcut: "Barre de recherche:",
favoriteShortcut: "Ajouter un favori:",
settingsShortcut: "Panneau des paramètres:",
historyShortcut: "Panneau d'historique:",
imagesShortcut: "Recherche d'images:",
shoppingShortcut: "Recherche shopping:",
newsShortcut: "Recherche actualités:",
searchHistory: "Historique de recherche",
clearHistory: "Effacer l'historique",
noHistory: "Aucun historique de recherche.",
account: "Compte",
login: "Se connecter",
register: "S'inscrire",
logout: "Se déconnecter",
welcome: "Bienvenue",
usernamePlaceholder: "Nom d'utilisateur",
passwordPlaceholder: "Mot de passe",
accountTitle: "Compte",
accountLogin: "Compte (Cliquez pour se connecter)",
accountLoggedIn: "Compte (Cliquez pour se déconnecter)",
accountError: "Nom d'utilisateur ou mot de passe incorrect.",
usernameTooShort: "Le nom d'utilisateur doit contenir au moins 2 caractères.",
passwordTooShort: "Le mot de passe doit contenir au moins 4 caractères.",
usernameTaken: "Ce nom d'utilisateur est déjà pris.",
confirm: "OK",
cancel: "Annuler",
voiceSearch: "Ce que vous dites apparaîtra ici...",
   aiProvider: "Fournisseur d'IA:",
    customAiUrl: "URL d'IA personnalisée:",
    showAISearch: "Afficher la recherche d'IA:",
    aiShortcut: "Recherche d'IA:",
    accountIcon: "Icône de compte",
    weather: "Météo:",
    weatherApi: "API Météo:",
    openWeatherMapApiKey: "Clé API OpenWeatherMap:",
    visualCrossingApiKey: "Clé API Visual Crossing:",
    weatherApiKey: "Clé API Météo:",
    aiSearch: "Recherche IA",
    settings: "Paramètres",
    history: "Historique",
    weatherLoading: "Chargement...",
    weatherError: "Impossible de charger les informations météo.",
    weatherLocationEmpty: "Veuillez entrer un lieu.",
    weatherApiKeyMissing: "Clé API manquante.",
    weatherClear: "Ensoleillé",
    weatherPartlyCloudy: "Partiellement nuageux",
    weatherCloudy: "Nuageux",
    weatherRain: "Pluvieux",
    weatherSnow: "Neigeux",
    weatherWindy: "Venteux",
    weatherFog: "Brumeux",
    weatherShower: "Averses",
    weatherLightRain: "Pluie légère",
    weatherError: "Impossible de charger les informations météo.",
        loading: "Chargement...",
        noLocation: "Veuillez entrer un lieu.",
        youtubeError: "Impossible de charger la vidéo YouTube.",
        resetConfirm: "Êtes-vous sûr de vouloir réinitialiser tous les paramètres et données ?",
        resetSuccess: "Le navigateur a été réinitialisé avec succès !"
},
ar: {
bgUrl: "رابط الخلفية:",
font: "الخط:",
theme: "الثيم:",
accentColor: "لون التركيز:",
language: "اللغة:",
logoDisplay: "عرض الشعار:",
system: "النظام",
searchEngine: "محرك البحث:",
showFavorites: "عرض المفضلة:",
maxFavorites: "الحد الأقصى للمفضلة:",
showSuggestions: "عرض اقتراحات البحث:",
showWeather: "عرض الطقس:",
weatherLocation: "موقع الطقس:",
showInfoBar: "عرض شريط المعلومات:",
weatherUpdateInterval: "فاصل تحديث الطقس:",
linkBehavior: "سلوك الرابط:",
apply: "تطبيق",
favoriteName: "الاسم:",
favoriteUrl: "الرابط:",
add: "إضافة",
search: "بحث",
images: "صور",
shopping: "تسوق",
news: "أخبار",
addFavorite: " + ",
dark: "داكن",
light: "فاتح",
logoOnly: "الشعار فقط",
logoAndName: "الشعار والاسم",
none: "لا شيء",
yes: "نعم",
no: "لا",
every5Min: "كل 5 دقائق",
every10Min: "كل 10 دقائق",
every30Min: "كل 30 دقيقة",
manual: "يدوي",
newTab: "فتح في تبويب جديد",
closeCurrent: "إغلاق الصفحة الحالية",
searchPlaceholder: "ابحث...",
favoritePlaceholder: "اسم المفضلة",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "اسم المدينة",
languageDisplay: "العربية",
maxFavoritesAlert: "تم الوصول إلى الحد الأقصى للمفضلة!",
invalidUrlAlert: "يرجى إدخال رابط صالح (مثال: https://example.com).",
voiceSearchNotSupported: "البحث الصوتي غير مدعوم في متصفحك. يرجى استخدام البحث النصي.",
weatherError: "تعذر تحميل معلومات الطقس.",
personalization: "الشخصنة",
shortcuts: "اختصارات لوحة المفاتيح",
searchShortcut: "شريط البحث:",
favoriteShortcut: "إضافة مفضلة:",
settingsShortcut: "لوحة الإعدادات:",
historyShortcut: "لوحة السجل:",
imagesShortcut: "بحث الصور:",
shoppingShortcut: "بحث التسوق:",
newsShortcut: "بحث الأخبار:",
searchHistory: "سجل البحث",
clearHistory: "مسح السجل",
noHistory: "لا يوجد سجل بحث.",
account: "الحساب",
login: "تسجيل الدخول",
register: "التسجيل",
logout: "تسجيل الخروج",
welcome: "مرحبا",
usernamePlaceholder: "اسم المستخدم",
passwordPlaceholder: "كلمة المرور",
accountTitle: "الحساب",
accountLogin: "الحساب (اضغط لتسجيل الدخول)",
accountLoggedIn: "الحساب (اضغط لتسجيل الخروج)",
accountError: "اسم المستخدم أو كلمة المرور غير صحيح.",
usernameTooShort: "اسم المستخدم يجب أن يكون على الأقل 2 أحرف.",
passwordTooShort: "كلمة المرور يجب أن تكون على الأقل 4 أحرف.",
usernameTaken: "اسم المستخدم هذا مستخدم بالفعل.",
confirm: "موافق",
cancel: "إلغاء",
voiceSearch: "ما تقوله سيظهر هنا...",
   aiProvider: "مزود الذكاء الاصطناعي:",
    customAiUrl: "عنوان URL مخصص للذكاء الاصطناعي:",
    showAISearch: "عرض بحث الذكاء الاصطناعي:",
    aiShortcut: "اختصار بحث الذكاء الاصطناعي:",
    accountIcon: "رمز الحساب",
    weather: "الطقس:",
    weatherApi: "API الطقس:",
    openWeatherMapApiKey: "مفتاح API لـ OpenWeatherMap:",
    visualCrossingApiKey: "مفتاح API لـ Visual Crossing:",
    weatherApiKey: "مفتاح API لـ الطقس:",
    aiSearch: "بحث الذكاء الاصطناعي",
    settings: "إعدادات",
    history: "سجل",
    weatherLoading: "جارٍ التحميل...",
    weatherError: "تعذر تحميل معلومات الطقس.",
    weatherLocationEmpty: "يرجى إدخال موقع.",
    weatherApiKeyMissing: "مفتاح API مفقود.",
            weatherClear: "صافي",
        weatherPartlyCloudy: "غائم جزئيًا",
        weatherCloudy: "غائم",
        weatherRain: "ممطر",
        weatherSnow: "ثلجي",
        weatherWindy: "عاصف",
        weatherFog: "ضبابي",
        weatherShower: "زخات",
        weatherLightRain: "مطر خفيف",
        weatherError: "تعذر تحميل معلومات الطقس.",
        loading: "جارٍ التحميل...",
        noLocation: "يرجى إدخال موقع.",
        youtubeError: "تعذر تحميل فيديو YouTube.",
        resetConfirm: "هل أنت متأكد أنك تريد إعادة تعيين جميع الإعدادات والبيانات؟",
        resetSuccess: "تم إعادة تعيين المتصفح بنجاح!"

},
ru: {
bgUrl: "URL фона:",
font: "Шрифт:",
theme: "Цветовая тема:",
accentColor: "Цвет акцента:",
language: "Язык:",
logoDisplay: "Отображение логотипа:",
system: "Система",
searchEngine: "Поисковая система:",
showFavorites: "Показать избранное:",
maxFavorites: "Максимальное количество избранного:",
showSuggestions: "Показать подсказки поиска:",
showWeather: "Показать погоду:",
weatherLocation: "Местоположение погоды:",
showInfoBar: "Показать информационную панель:",
weatherUpdateInterval: "Частота обновления погоды:",
linkBehavior: "Поведение ссылки:",
apply: "Применить",
favoriteName: "Название:",
favoriteUrl: "URL:",
add: "Добавить",
search: "Поиск",
images: "Изображения",
shopping: "Покупки",
news: "Новости",
addFavorite: " + ",
dark: "Темная",
light: "Светлая",
logoOnly: "Только логотип",
logoAndName: "Логотип и название",
none: "Ничего",
yes: "Да",
no: "Нет",
every5Min: "Каждые 5 минут",
every10Min: "Каждые 10 минут",
every30Min: "Каждые 30 минут",
manual: "Вручную",
newTab: "Открыть в новой вкладке",
closeCurrent: "Закрыть эту страницу",
searchPlaceholder: "Поиск...",
favoritePlaceholder: "Название избранного",
urlPlaceholder: "https://...",
weatherLocationPlaceholder: "Название города",
languageDisplay: "Русский",
maxFavoritesAlert: "Достигнуто максимальное количество избранного!",
invalidUrlAlert: "Введите действительный URL (например, https://example.com).",
voiceSearchNotSupported: "Голосовой поиск не поддерживается в вашем браузере. Используйте текстовый поиск.",
weatherError: "Не удалось загрузить погоду.",
personalization: "Персонализация",
shortcuts: "Горячие клавиши",
searchShortcut: "Строка поиска:",
favoriteShortcut: "Добавить в избранное:",
settingsShortcut: "Панель настроек:",
historyShortcut: "Панель истории:",
imagesShortcut: "Поиск изображений:",
shoppingShortcut: "Поиск покупок:",
newsShortcut: "Поиск новостей:",
searchHistory: "История поиска",
clearHistory: "Очистить историю",
noHistory: "Нет истории поиска.",
account: "Аккаунт",
login: "Войти",
register: "Зарегистрироваться",
logout: "Выйти",
welcome: "Добро пожаловать",
usernamePlaceholder: "Имя пользователя",
passwordPlaceholder: "Пароль",
accountTitle: "Аккаунт",
accountLogin: "Аккаунт (Нажмите для входа)",
accountLoggedIn: "Аккаунт (Нажмите для выхода)",
accountError: "Неверное имя пользователя или пароль.",
usernameTooShort: "Имя пользователя должно быть не менее 2 символов.",
passwordTooShort: "Пароль должен быть не менее 4 символов.",
usernameTaken: "Это имя пользователя уже занято.",
confirm: "OK",
cancel: "Отмена",
voiceSearch: "Ваш текст появится здесь...",
   aiProvider: "AI Провайдер:",
    customAiUrl: "Пользовательский AI URL:",
    showAISearch: "Показать AI Поиск:",
    aiShortcut: "AI Поиск:",
    accountIcon: "Иконка аккаунта",
    weather: "Погода:",
    weatherApi: "API Погоды:",
    openWeatherMapApiKey: "Ключ API OpenWeatherMap:",
    visualCrossingApiKey: "Ключ API Visual Crossing:",
    weatherApiKey: "Ключ API Погоды:",
    aiSearch: "Поиск ИИ",
    settings: "Настройки",
    history: "История",
    weatherLoading: "Загрузка...",
    weatherError: "Не удалось загрузить погоду.",
    weatherLocationEmpty: "Введите местоположение.",
    weatherApiKeyMissing: "Отсутствует ключ API.",
    weatherClear: "Солнечно",
    weatherPartlyCloudy: "Частично облачно",
    weatherCloudy: "Облачно",
    weatherRain: "Дождливо",
    weatherSnow: "Снежно",
    weatherWindy: "Ветреная",
    weatherFog: "Туманно",
    weatherShower: "Ливень",
    weatherLightRain: "Небольшой дождь",
    weatherError: "Ошибка загрузки погоды.",
        loading: "Загрузка...",
        noLocation: "Введите местоположение.",
        youtubeError: "Не удалось загрузить видео с YouTube.",
        resetConfirm: "Вы уверены, что хотите сбросить все настройки и данные?",
        resetSuccess: "Браузер успешно сброшен!"


},
};
export { translations };
